export { PersonAvatar as Avatar } from './PersonAvatar'
export { PersonFollowInfo as FollowInfo } from './PersonFollowInfo'
export { PersonName as Name } from './PersonName'
export { PersonNickname as Nickname } from './PersonNickname'
export { PersonLastActivity as LastActivity } from './PersonLastActivity'
