// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  type UseMutationOptions,
  infiniteQueryOptions,
  queryOptions
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  type Options,
  authControllerLogin,
  authControllerLogout,
  authControllerRefresh,
  authControllerRegister,
  postControllerCreate,
  postControllerCreateComment,
  postControllerCreateLike,
  postControllerFindAll,
  postControllerFindAllComments,
  postControllerFindAllLikes,
  postControllerFindOne,
  postControllerRemove,
  postControllerRemoveComment,
  postControllerRemoveLike,
  postControllerUpdate,
  postControllerUpdateComment,
  profileControllerMe,
  profileControllerMeDetailed,
  profileControllerUpdate,
  subscriptionControllerFindAllFollowers,
  subscriptionControllerFindAllFollowing,
  subscriptionControllerFindOneCount,
  subscriptionControllerFollow,
  subscriptionControllerUnfollow,
  uploadControllerDelete,
  uploadControllerUpload,
  userControllerChangePassword,
  userControllerFindAll,
  userControllerFindOne,
  userControllerRemove,
  userControllerUpdate
} from '../sdk.gen'

import type {
  AuthControllerLoginData,
  AuthControllerLoginResponse,
  AuthControllerLogoutData,
  AuthControllerLogoutResponse,
  AuthControllerRefreshData,
  AuthControllerRefreshResponse,
  AuthControllerRegisterData,
  AuthControllerRegisterResponse,
  PostControllerCreateCommentData,
  PostControllerCreateCommentResponse,
  PostControllerCreateData,
  PostControllerCreateLikeData,
  PostControllerCreateLikeResponse,
  PostControllerCreateResponse,
  PostControllerFindAllCommentsData,
  PostControllerFindAllCommentsResponse,
  PostControllerFindAllData,
  PostControllerFindAllLikesData,
  PostControllerFindAllLikesResponse,
  PostControllerFindAllResponse,
  PostControllerFindOneData,
  PostControllerRemoveCommentData,
  PostControllerRemoveCommentResponse,
  PostControllerRemoveData,
  PostControllerRemoveLikeData,
  PostControllerRemoveLikeResponse,
  PostControllerRemoveResponse,
  PostControllerUpdateCommentData,
  PostControllerUpdateCommentResponse,
  PostControllerUpdateData,
  PostControllerUpdateResponse,
  ProfileControllerMeData,
  ProfileControllerMeDetailedData,
  ProfileControllerUpdateData,
  ProfileControllerUpdateResponse,
  SubscriptionControllerFindAllFollowersData,
  SubscriptionControllerFindAllFollowersResponse,
  SubscriptionControllerFindAllFollowingData,
  SubscriptionControllerFindAllFollowingResponse,
  SubscriptionControllerFindOneCountData,
  SubscriptionControllerFollowData,
  SubscriptionControllerFollowResponse,
  SubscriptionControllerUnfollowData,
  SubscriptionControllerUnfollowResponse,
  UploadControllerDeleteData,
  UploadControllerDeleteResponse,
  UploadControllerUploadData,
  UploadControllerUploadResponse,
  UserControllerChangePasswordData,
  UserControllerChangePasswordResponse,
  UserControllerFindAllData,
  UserControllerFindAllResponse,
  UserControllerFindOneData,
  UserControllerRemoveData,
  UserControllerRemoveResponse,
  UserControllerUpdateData,
  UserControllerUpdateResponse
} from '../types.gen'
import type { AxiosError } from 'axios'

/**
 * Validation pattern for password:
 * `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$/`
 */
export const authControllerRegisterMutation = (
  options?: Partial<Options<AuthControllerRegisterData>>
): UseMutationOptions<
  AuthControllerRegisterResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRegisterResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRegister({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerLoginMutation = (
  options?: Partial<Options<AuthControllerLoginData>>
): UseMutationOptions<
  AuthControllerLoginResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLoginResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogin({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerLogoutMutation = (
  options?: Partial<Options<AuthControllerLogoutData>>
): UseMutationOptions<
  AuthControllerLogoutResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLogoutResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogout({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerRefreshMutation = (
  options?: Partial<Options<AuthControllerRefreshData>>
): UseMutationOptions<
  AuthControllerRefreshResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRefreshData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRefreshResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const userControllerFindAllQueryKey = (
  options?: Options<UserControllerFindAllData>
) => createQueryKey('userControllerFindAll', options)

export const userControllerFindAllOptions = (
  options?: Options<UserControllerFindAllData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: userControllerFindAllQueryKey(options)
  })
}

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {
    ...queryKey[0]
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any)
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any)
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any)
    }
  }
  return params as unknown as typeof page
}

export const userControllerFindAllInfiniteQueryKey = (
  options?: Options<UserControllerFindAllData>
): QueryKey<Options<UserControllerFindAllData>> =>
  createQueryKey('userControllerFindAll', options, true)

export const userControllerFindAllInfiniteOptions = (
  options?: Options<UserControllerFindAllData>
) => {
  return infiniteQueryOptions<
    UserControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<UserControllerFindAllResponse>,
    QueryKey<Options<UserControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<UserControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<UserControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await userControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: userControllerFindAllInfiniteQueryKey(options)
    }
  )
}

export const userControllerRemoveMutation = (
  options?: Partial<Options<UserControllerRemoveData>>
): UseMutationOptions<
  UserControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<UserControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<UserControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const userControllerFindOneQueryKey = (
  options: Options<UserControllerFindOneData>
) => createQueryKey('userControllerFindOne', options)

export const userControllerFindOneOptions = (
  options: Options<UserControllerFindOneData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: userControllerFindOneQueryKey(options)
  })
}

export const userControllerUpdateMutation = (
  options?: Partial<Options<UserControllerUpdateData>>
): UseMutationOptions<
  UserControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<UserControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<UserControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const userControllerChangePasswordMutation = (
  options?: Partial<Options<UserControllerChangePasswordData>>
): UseMutationOptions<
  UserControllerChangePasswordResponse,
  AxiosError<DefaultError>,
  Options<UserControllerChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerChangePasswordResponse,
    AxiosError<DefaultError>,
    Options<UserControllerChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const profileControllerMeQueryKey = (
  options?: Options<ProfileControllerMeData>
) => createQueryKey('profileControllerMe', options)

export const profileControllerMeOptions = (
  options?: Options<ProfileControllerMeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await profileControllerMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: profileControllerMeQueryKey(options)
  })
}

export const profileControllerMeDetailedQueryKey = (
  options?: Options<ProfileControllerMeDetailedData>
) => createQueryKey('profileControllerMeDetailed', options)

export const profileControllerMeDetailedOptions = (
  options?: Options<ProfileControllerMeDetailedData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await profileControllerMeDetailed({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: profileControllerMeDetailedQueryKey(options)
  })
}

export const profileControllerUpdateMutation = (
  options?: Partial<Options<ProfileControllerUpdateData>>
): UseMutationOptions<
  ProfileControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<ProfileControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    ProfileControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<ProfileControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await profileControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerFindAllQueryKey = (
  options?: Options<PostControllerFindAllData>
) => createQueryKey('postControllerFindAll', options)

export const postControllerFindAllOptions = (
  options?: Options<PostControllerFindAllData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: postControllerFindAllQueryKey(options)
  })
}

export const postControllerFindAllInfiniteQueryKey = (
  options?: Options<PostControllerFindAllData>
): QueryKey<Options<PostControllerFindAllData>> =>
  createQueryKey('postControllerFindAll', options, true)

export const postControllerFindAllInfiniteOptions = (
  options?: Options<PostControllerFindAllData>
) => {
  return infiniteQueryOptions<
    PostControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostControllerFindAllResponse>,
    QueryKey<Options<PostControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<PostControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: postControllerFindAllInfiniteQueryKey(options)
    }
  )
}

export const postControllerCreateMutation = (
  options?: Partial<Options<PostControllerCreateData>>
): UseMutationOptions<
  PostControllerCreateResponse,
  AxiosError<DefaultError>,
  Options<PostControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerCreateResponse,
    AxiosError<DefaultError>,
    Options<PostControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerFindAllCommentsQueryKey = (
  options: Options<PostControllerFindAllCommentsData>
) => createQueryKey('postControllerFindAllComments', options)

export const postControllerFindAllCommentsOptions = (
  options: Options<PostControllerFindAllCommentsData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postControllerFindAllComments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: postControllerFindAllCommentsQueryKey(options)
  })
}

export const postControllerFindAllCommentsInfiniteQueryKey = (
  options: Options<PostControllerFindAllCommentsData>
): QueryKey<Options<PostControllerFindAllCommentsData>> =>
  createQueryKey('postControllerFindAllComments', options, true)

export const postControllerFindAllCommentsInfiniteOptions = (
  options: Options<PostControllerFindAllCommentsData>
) => {
  return infiniteQueryOptions<
    PostControllerFindAllCommentsResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostControllerFindAllCommentsResponse>,
    QueryKey<Options<PostControllerFindAllCommentsData>>,
    | number
    | Pick<
        QueryKey<Options<PostControllerFindAllCommentsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostControllerFindAllCommentsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postControllerFindAllComments({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: postControllerFindAllCommentsInfiniteQueryKey(options)
    }
  )
}

export const postControllerCreateCommentMutation = (
  options?: Partial<Options<PostControllerCreateCommentData>>
): UseMutationOptions<
  PostControllerCreateCommentResponse,
  AxiosError<DefaultError>,
  Options<PostControllerCreateCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerCreateCommentResponse,
    AxiosError<DefaultError>,
    Options<PostControllerCreateCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerCreateComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerRemoveLikeMutation = (
  options?: Partial<Options<PostControllerRemoveLikeData>>
): UseMutationOptions<
  PostControllerRemoveLikeResponse,
  AxiosError<DefaultError>,
  Options<PostControllerRemoveLikeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerRemoveLikeResponse,
    AxiosError<DefaultError>,
    Options<PostControllerRemoveLikeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerRemoveLike({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerFindAllLikesQueryKey = (
  options: Options<PostControllerFindAllLikesData>
) => createQueryKey('postControllerFindAllLikes', options)

export const postControllerFindAllLikesOptions = (
  options: Options<PostControllerFindAllLikesData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postControllerFindAllLikes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: postControllerFindAllLikesQueryKey(options)
  })
}

export const postControllerFindAllLikesInfiniteQueryKey = (
  options: Options<PostControllerFindAllLikesData>
): QueryKey<Options<PostControllerFindAllLikesData>> =>
  createQueryKey('postControllerFindAllLikes', options, true)

export const postControllerFindAllLikesInfiniteOptions = (
  options: Options<PostControllerFindAllLikesData>
) => {
  return infiniteQueryOptions<
    PostControllerFindAllLikesResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostControllerFindAllLikesResponse>,
    QueryKey<Options<PostControllerFindAllLikesData>>,
    | number
    | Pick<
        QueryKey<Options<PostControllerFindAllLikesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostControllerFindAllLikesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postControllerFindAllLikes({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: postControllerFindAllLikesInfiniteQueryKey(options)
    }
  )
}

export const postControllerCreateLikeMutation = (
  options?: Partial<Options<PostControllerCreateLikeData>>
): UseMutationOptions<
  PostControllerCreateLikeResponse,
  AxiosError<DefaultError>,
  Options<PostControllerCreateLikeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerCreateLikeResponse,
    AxiosError<DefaultError>,
    Options<PostControllerCreateLikeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerCreateLike({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerRemoveMutation = (
  options?: Partial<Options<PostControllerRemoveData>>
): UseMutationOptions<
  PostControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<PostControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<PostControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerFindOneQueryKey = (
  options: Options<PostControllerFindOneData>
) => createQueryKey('postControllerFindOne', options)

export const postControllerFindOneOptions = (
  options: Options<PostControllerFindOneData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: postControllerFindOneQueryKey(options)
  })
}

export const postControllerUpdateMutation = (
  options?: Partial<Options<PostControllerUpdateData>>
): UseMutationOptions<
  PostControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<PostControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<PostControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerRemoveCommentMutation = (
  options?: Partial<Options<PostControllerRemoveCommentData>>
): UseMutationOptions<
  PostControllerRemoveCommentResponse,
  AxiosError<DefaultError>,
  Options<PostControllerRemoveCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerRemoveCommentResponse,
    AxiosError<DefaultError>,
    Options<PostControllerRemoveCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerRemoveComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const postControllerUpdateCommentMutation = (
  options?: Partial<Options<PostControllerUpdateCommentData>>
): UseMutationOptions<
  PostControllerUpdateCommentResponse,
  AxiosError<DefaultError>,
  Options<PostControllerUpdateCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostControllerUpdateCommentResponse,
    AxiosError<DefaultError>,
    Options<PostControllerUpdateCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postControllerUpdateComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const uploadControllerUploadMutation = (
  options?: Partial<Options<UploadControllerUploadData>>
): UseMutationOptions<
  UploadControllerUploadResponse,
  AxiosError<DefaultError>,
  Options<UploadControllerUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadControllerUploadResponse,
    AxiosError<DefaultError>,
    Options<UploadControllerUploadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadControllerUpload({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const uploadControllerDeleteMutation = (
  options?: Partial<Options<UploadControllerDeleteData>>
): UseMutationOptions<
  UploadControllerDeleteResponse,
  AxiosError<DefaultError>,
  Options<UploadControllerDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadControllerDeleteResponse,
    AxiosError<DefaultError>,
    Options<UploadControllerDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadControllerDelete({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const subscriptionControllerFindAllFollowersQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) => createQueryKey('subscriptionControllerFindAllFollowers', options)

export const subscriptionControllerFindAllFollowersOptions = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindAllFollowers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: subscriptionControllerFindAllFollowersQueryKey(options)
  })
}

export const subscriptionControllerFindAllFollowersInfiniteQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowersData>
): QueryKey<Options<SubscriptionControllerFindAllFollowersData>> =>
  createQueryKey('subscriptionControllerFindAllFollowers', options, true)

export const subscriptionControllerFindAllFollowersInfiniteOptions = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) => {
  return infiniteQueryOptions<
    SubscriptionControllerFindAllFollowersResponse,
    AxiosError<DefaultError>,
    InfiniteData<SubscriptionControllerFindAllFollowersResponse>,
    QueryKey<Options<SubscriptionControllerFindAllFollowersData>>,
    | number
    | Pick<
        QueryKey<Options<SubscriptionControllerFindAllFollowersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubscriptionControllerFindAllFollowersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await subscriptionControllerFindAllFollowers({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: subscriptionControllerFindAllFollowersInfiniteQueryKey(options)
    }
  )
}

export const subscriptionControllerFindAllFollowingQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) => createQueryKey('subscriptionControllerFindAllFollowing', options)

export const subscriptionControllerFindAllFollowingOptions = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindAllFollowing({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: subscriptionControllerFindAllFollowingQueryKey(options)
  })
}

export const subscriptionControllerFindAllFollowingInfiniteQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowingData>
): QueryKey<Options<SubscriptionControllerFindAllFollowingData>> =>
  createQueryKey('subscriptionControllerFindAllFollowing', options, true)

export const subscriptionControllerFindAllFollowingInfiniteOptions = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) => {
  return infiniteQueryOptions<
    SubscriptionControllerFindAllFollowingResponse,
    AxiosError<DefaultError>,
    InfiniteData<SubscriptionControllerFindAllFollowingResponse>,
    QueryKey<Options<SubscriptionControllerFindAllFollowingData>>,
    | number
    | Pick<
        QueryKey<Options<SubscriptionControllerFindAllFollowingData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubscriptionControllerFindAllFollowingData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await subscriptionControllerFindAllFollowing({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: subscriptionControllerFindAllFollowingInfiniteQueryKey(options)
    }
  )
}

export const subscriptionControllerFindOneCountQueryKey = (
  options: Options<SubscriptionControllerFindOneCountData>
) => createQueryKey('subscriptionControllerFindOneCount', options)

export const subscriptionControllerFindOneCountOptions = (
  options: Options<SubscriptionControllerFindOneCountData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindOneCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: subscriptionControllerFindOneCountQueryKey(options)
  })
}

export const subscriptionControllerFollowMutation = (
  options?: Partial<Options<SubscriptionControllerFollowData>>
): UseMutationOptions<
  SubscriptionControllerFollowResponse,
  AxiosError<DefaultError>,
  Options<SubscriptionControllerFollowData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscriptionControllerFollowResponse,
    AxiosError<DefaultError>,
    Options<SubscriptionControllerFollowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await subscriptionControllerFollow({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const subscriptionControllerUnfollowMutation = (
  options?: Partial<Options<SubscriptionControllerUnfollowData>>
): UseMutationOptions<
  SubscriptionControllerUnfollowResponse,
  AxiosError<DefaultError>,
  Options<SubscriptionControllerUnfollowData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscriptionControllerUnfollowResponse,
    AxiosError<DefaultError>,
    Options<SubscriptionControllerUnfollowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await subscriptionControllerUnfollow({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}
