// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  type UseMutationOptions,
  infiniteQueryOptions,
  queryOptions
} from '@tanstack/react-query'


import { client } from '../client.gen'
import {
  type Options,
  authControllerLogin,
  authControllerLogout,
  authControllerRefresh,
  authControllerRegister,
  profileControllerFindOne,
  userControllerFindAll,
  userControllerFindOne,
  userControllerRemove,
  userControllerUpdate
} from '../sdk.gen'

import type {
  AuthControllerLoginData,
  AuthControllerLoginResponse,
  AuthControllerLogoutData,
  AuthControllerLogoutResponse,
  AuthControllerRefreshData,
  AuthControllerRefreshResponse,
  AuthControllerRegisterData,
  AuthControllerRegisterResponse,
  ProfileControllerFindOneData,
  UserControllerFindAllData,
  UserControllerFindAllResponse,
  UserControllerFindOneData,
  UserControllerRemoveData,
  UserControllerRemoveResponse,
  UserControllerUpdateData,
  UserControllerUpdateResponse
} from '../types.gen'
import type { AxiosError } from 'axios'

export const authControllerRegisterMutation = (
  options?: Partial<Options<AuthControllerRegisterData>>
): UseMutationOptions<
  AuthControllerRegisterResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRegisterResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRegister({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerLoginMutation = (
  options?: Partial<Options<AuthControllerLoginData>>
): UseMutationOptions<
  AuthControllerLoginResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLoginResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogin({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerLogoutMutation = (
  options?: Partial<Options<AuthControllerLogoutData>>
): UseMutationOptions<
  AuthControllerLogoutResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLogoutResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogout({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const authControllerRefreshMutation = (
  options?: Partial<Options<AuthControllerRefreshData>>
): UseMutationOptions<
  AuthControllerRefreshResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRefreshData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRefreshResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const userControllerFindAllQueryKey = (
  options?: Options<UserControllerFindAllData>
) => createQueryKey('userControllerFindAll', options)

export const userControllerFindAllOptions = (
  options?: Options<UserControllerFindAllData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: userControllerFindAllQueryKey(options)
  })
}

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {
    ...queryKey[0]
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any)
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any)
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any)
    }
  }
  return params as unknown as typeof page
}

export const userControllerFindAllInfiniteQueryKey = (
  options?: Options<UserControllerFindAllData>
): QueryKey<Options<UserControllerFindAllData>> =>
  createQueryKey('userControllerFindAll', options, true)

export const userControllerFindAllInfiniteOptions = (
  options?: Options<UserControllerFindAllData>
) => {
  return infiniteQueryOptions<
    UserControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<UserControllerFindAllResponse>,
    QueryKey<Options<UserControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<UserControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<UserControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await userControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })

        return data
      },
      queryKey: userControllerFindAllInfiniteQueryKey(options)
    }
  )
}

export const userControllerRemoveMutation = (
  options?: Partial<Options<UserControllerRemoveData>>
): UseMutationOptions<
  UserControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<UserControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<UserControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const userControllerFindOneQueryKey = (
  options: Options<UserControllerFindOneData>
) => createQueryKey('userControllerFindOne', options)

export const userControllerFindOneOptions = (
  options: Options<UserControllerFindOneData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: userControllerFindOneQueryKey(options)
  })
}

export const userControllerUpdateMutation = (
  options?: Partial<Options<UserControllerUpdateData>>
): UseMutationOptions<
  UserControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<UserControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<UserControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })

      return data
    }
  }

  return mutationOptions
}

export const profileControllerFindOneQueryKey = (
  options?: Options<ProfileControllerFindOneData>
) => createQueryKey('profileControllerFindOne', options)

export const profileControllerFindOneOptions = (
  options?: Options<ProfileControllerFindOneData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await profileControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })

      return data
    },
    queryKey: profileControllerFindOneQueryKey(options)
  })
}
