// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape
} from './client'
import { client } from './client.gen'
import type {
  AuthControllerLoginData,
  AuthControllerLoginResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterResponses,
  ConversationControllerCreateData,
  ConversationControllerCreateResponses,
  ConversationControllerFindAllConversationMessagesData,
  ConversationControllerFindAllConversationMessagesResponses,
  ConversationControllerFindAllData,
  ConversationControllerFindAllResponses,
  ConversationControllerFindAllSuggestionsData,
  ConversationControllerFindAllSuggestionsResponses,
  ConversationControllerFindOneData,
  ConversationControllerFindOneResponses,
  ConversationControllerRemoveData,
  ConversationControllerRemoveResponses,
  MessageControllerCreateData,
  MessageControllerCreateResponses,
  MessageControllerFindOneData,
  MessageControllerFindOneResponses,
  MessageControllerRemoveData,
  MessageControllerRemoveResponses,
  MessageControllerUpdateData,
  MessageControllerUpdateResponses,
  PostControllerCreateCommentData,
  PostControllerCreateCommentResponses,
  PostControllerCreateData,
  PostControllerCreateLikeData,
  PostControllerCreateLikeResponses,
  PostControllerCreateResponses,
  PostControllerFindAllCommentsData,
  PostControllerFindAllCommentsResponses,
  PostControllerFindAllData,
  PostControllerFindAllLikesData,
  PostControllerFindAllLikesResponses,
  PostControllerFindAllResponses,
  PostControllerFindOneData,
  PostControllerFindOneResponses,
  PostControllerRemoveCommentData,
  PostControllerRemoveCommentResponses,
  PostControllerRemoveData,
  PostControllerRemoveLikeData,
  PostControllerRemoveLikeResponses,
  PostControllerRemoveResponses,
  PostControllerUpdateCommentData,
  PostControllerUpdateCommentResponses,
  PostControllerUpdateData,
  PostControllerUpdateResponses,
  ProfileControllerMeData,
  ProfileControllerMeDetailedData,
  ProfileControllerMeDetailedResponses,
  ProfileControllerMeResponses,
  ProfileControllerUpdateData,
  ProfileControllerUpdateResponses,
  SubscriptionControllerFindAllFollowersData,
  SubscriptionControllerFindAllFollowersResponses,
  SubscriptionControllerFindAllFollowingData,
  SubscriptionControllerFindAllFollowingResponses,
  SubscriptionControllerFindOneCountData,
  SubscriptionControllerFindOneCountResponses,
  SubscriptionControllerFollowData,
  SubscriptionControllerFollowResponses,
  SubscriptionControllerUnfollowData,
  SubscriptionControllerUnfollowResponses,
  UploadControllerDeleteData,
  UploadControllerDeleteResponses,
  UploadControllerUploadData,
  UploadControllerUploadResponses,
  UserControllerChangePasswordData,
  UserControllerChangePasswordResponses,
  UserControllerFindAllData,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneResponses,
  UserControllerRemoveData,
  UserControllerRemoveResponses,
  UserControllerUpdateData,
  UserControllerUpdateResponses
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Validation pattern for password:
 * `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$/`
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    AuthControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    AuthControllerLoginResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/logout',
    ...options
  })
}

export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/refresh',
    ...options
  })
}

export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    UserControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users',
    ...options
  })
}

export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    UserControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options
  })
}

export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    UserControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options
  })
}

export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    UserControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const userControllerChangePassword = <
  ThrowOnError extends boolean = false
>(
  options: Options<UserControllerChangePasswordData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    UserControllerChangePasswordResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const profileControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<ProfileControllerMeData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ProfileControllerMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/profile/me',
    ...options
  })
}

export const profileControllerMeDetailed = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ProfileControllerMeDetailedData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ProfileControllerMeDetailedResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/profile/me/detailed',
    ...options
  })
}

export const profileControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProfileControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    ProfileControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const postControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostControllerFindAllData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    PostControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts',
    ...options
  })
}

export const postControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerCreateData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const postControllerFindAllComments = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostControllerFindAllCommentsData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    PostControllerFindAllCommentsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/comments',
    ...options
  })
}

export const postControllerCreateComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostControllerCreateCommentData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostControllerCreateCommentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/comments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const postControllerRemoveLike = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerRemoveLikeData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    PostControllerRemoveLikeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/likes',
    ...options
  })
}

export const postControllerFindAllLikes = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostControllerFindAllLikesData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    PostControllerFindAllLikesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/likes',
    ...options
  })
}

export const postControllerCreateLike = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerCreateLikeData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostControllerCreateLikeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/likes',
    ...options
  })
}

export const postControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    PostControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}',
    ...options
  })
}

export const postControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    PostControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}',
    ...options
  })
}

export const postControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PostControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PostControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const postControllerRemoveComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostControllerRemoveCommentData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    PostControllerRemoveCommentResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/comments/{commentId}',
    ...options
  })
}

export const postControllerUpdateComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostControllerUpdateCommentData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PostControllerUpdateCommentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/posts/{id}/comments/{commentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const uploadControllerUpload = <ThrowOnError extends boolean = false>(
  options: Options<UploadControllerUploadData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    UploadControllerUploadResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers
    }
  })
}

export const uploadControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<UploadControllerDeleteData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    UploadControllerDeleteResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/upload/{id}',
    ...options
  })
}

export const messageControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    MessageControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/messages/{id}',
    ...options
  })
}

export const messageControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    MessageControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/messages/{id}',
    ...options
  })
}

export const messageControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    MessageControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/messages/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const messageControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerCreateData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    MessageControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const subscriptionControllerFindAllFollowers = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindAllFollowersData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    SubscriptionControllerFindAllFollowersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/subscription/followers/{id}',
    ...options
  })
}

export const subscriptionControllerFindAllFollowing = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindAllFollowingData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    SubscriptionControllerFindAllFollowingResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/subscription/following/{id}',
    ...options
  })
}

export const subscriptionControllerFindOneCount = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindOneCountData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    SubscriptionControllerFindOneCountResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/subscription/count/{id}',
    ...options
  })
}

export const subscriptionControllerFollow = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFollowData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    SubscriptionControllerFollowResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/subscription/follow/{id}',
    ...options
  })
}

export const subscriptionControllerUnfollow = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerUnfollowData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    SubscriptionControllerUnfollowResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/subscription/unfollow/{id}',
    ...options
  })
}

export const conversationControllerFindAll = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ConversationControllerFindAllData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ConversationControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations',
    ...options
  })
}

export const conversationControllerCreate = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerCreateData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    ConversationControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const conversationControllerFindAllSuggestions = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ConversationControllerFindAllSuggestionsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ConversationControllerFindAllSuggestionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations/suggestions',
    ...options
  })
}

export const conversationControllerFindAllConversationMessages = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    ConversationControllerFindAllConversationMessagesData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).get<
    ConversationControllerFindAllConversationMessagesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations/{id}/messages',
    ...options
  })
}

export const conversationControllerRemove = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    ConversationControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations/{id}',
    ...options
  })
}

export const conversationControllerFindOne = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ConversationControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/conversations/{id}',
    ...options
  })
}
