// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen'

import type { Client, Options as Options2, TDataShape } from './client'
import type {
  AuthControllerLoginData,
  AuthControllerLoginResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterResponses,
  ProfileControllerFindOneData,
  ProfileControllerFindOneResponses,
  UserControllerFindAllData,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneResponses,
  UserControllerRemoveData,
  UserControllerRemoveResponses,
  UserControllerUpdateData,
  UserControllerUpdateResponses
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    AuthControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    AuthControllerLoginResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/logout',
    ...options
  })
}

export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/refresh',
    ...options
  })
}

export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    UserControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users',
    ...options
  })
}

export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    UserControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options
  })
}

export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    UserControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options
  })
}

export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    UserControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })
}

export const profileControllerFindOne = <ThrowOnError extends boolean = false>(
  options?: Options<ProfileControllerFindOneData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ProfileControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [
      {
        scheme: 'bearer',
        type: 'http'
      }
    ],
    url: '/api/profile/me',
    ...options
  })
}
