// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string
}

export type ResponseProfileDto = {
  readonly id: number
  fullName: string
  avatarUrl?: string | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
  readonly createdAt: string
}

export type ResponseUserProfileDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
}

export type ResponseRegisterDto = {
  user: ResponseUserProfileDto
  accessToken: string
}

export type BaseResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
}

export type CreateUserDto = {
  email: string
  username: string
  fullName: string
  password: string
}

export type ResponseLoginDto = {
  user: ResponseUserProfileDto
  accessToken: string
}

export type CreateLoginDto = {
  email: string
  password: string
}

export type EmptyResponseDto = {
  [key: string]: unknown
}

export type ResponseRefreshDto = {
  readonly accessToken: string
}

export type ResponseSubscriptionDto = {
  readonly id: number
  user: ResponseUserProfileDto
  readonly createdAt: string
}

export type ResponseUserDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  following?: Array<ResponseSubscriptionDto> | null
  followers?: Array<ResponseSubscriptionDto> | null
  readonly createdAt: string
}

export type PaginatedResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
  total: number
  page: number
  pageSize: number
  totalPages: number
  nextPage: number
  prevPage: number
}

export type UpdateUserDto = {
  email?: string
  username?: string
}

export type CreateChangePasswordDto = {
  oldPassword: string
  newPassword: string
}

export type ResponseProfileDetailedDto = {
  user: ResponseUserDto
}

export type UpdateProfileDto = {
  phone?: string | null
  biography?: string | null
  fullName?: string
  avatarUrl?: string | null
  birthDay?: string | null
}

export type ResponsePostFileDto = {
  readonly id: number
  url: string
  type?: string | null
  readonly uploadedAt: string
}

export type ResponsePostLikeDto = {
  readonly id: number
  user: ResponseUserProfileDto
  readonly createdAt: string
}

export type ResponsePostCommentDto = {
  readonly id: number
  readonly postId: number
  user: ResponseUserProfileDto
  content: string
  readonly createdAt: string
}

export type ResponsePostDto = {
  readonly id: number
  content: string
  user: ResponseUserDto
  files?: Array<ResponsePostFileDto> | null
  likes?: Array<ResponsePostLikeDto> | null
  comments?: Array<ResponsePostCommentDto> | null
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreatePostDto = {
  content: string
}

export type UpdatePostDto = {
  content?: string
}

export type CreateUploadAvatarDto = {
  file: Blob | File
}

export type ResponseProfileDtoWritable = {
  fullName: string
  avatarUrl?: string | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
}

export type ResponseUserProfileDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type EmptyResponseDtoWritable = {
  [key: string]: unknown
}

export type ResponseSubscriptionDtoWritable = {
  user: ResponseUserProfileDtoWritable
}

export type ResponseUserDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
  following?: Array<ResponseSubscriptionDtoWritable> | null
  followers?: Array<ResponseSubscriptionDtoWritable> | null
}

export type ResponsePostFileDtoWritable = {
  url: string
  type?: string | null
}

export type ResponsePostLikeDtoWritable = {
  user: ResponseUserProfileDtoWritable
}

export type ResponsePostCommentDtoWritable = {
  user: ResponseUserProfileDtoWritable
  content: string
}

export type ResponsePostDtoWritable = {
  content: string
  user: ResponseUserDtoWritable
  files?: Array<ResponsePostFileDtoWritable> | null
  likes?: Array<ResponsePostLikeDtoWritable> | null
  comments?: Array<ResponsePostCommentDtoWritable> | null
}

export type AuthControllerRegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/api/auth/register'
}

export type AuthControllerRegisterResponses = {
  200: BaseResponseDto & {
    data?: ResponseRegisterDto
  }
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: CreateLoginDto
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type AuthControllerLoginResponses = {
  200: BaseResponseDto & {
    data?: ResponseLoginDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/logout'
}

export type AuthControllerLogoutResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses]

export type AuthControllerRefreshData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/refresh'
}

export type AuthControllerRefreshResponses = {
  200: BaseResponseDto & {
    data?: ResponseRefreshDto
  }
}

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses]

export type UserControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/users'
}

export type UserControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseUserDto>
  }
}

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses]

export type UserControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerRemoveResponses = {
  204: void
}

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses]

export type UserControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses]

export type UserControllerUpdateData = {
  body: UpdateUserDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses]

export type UserControllerChangePasswordData = {
  body: CreateChangePasswordDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}/change-password'
}

export type UserControllerChangePasswordResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type UserControllerChangePasswordResponse =
  UserControllerChangePasswordResponses[keyof UserControllerChangePasswordResponses]

export type ProfileControllerMeData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me'
}

export type ProfileControllerMeResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerMeResponse =
  ProfileControllerMeResponses[keyof ProfileControllerMeResponses]

export type ProfileControllerMeDetailedData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me/detailed'
}

export type ProfileControllerMeDetailedResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDetailedDto
  }
}

export type ProfileControllerMeDetailedResponse =
  ProfileControllerMeDetailedResponses[keyof ProfileControllerMeDetailedResponses]

export type ProfileControllerUpdateData = {
  body: UpdateProfileDto
  path?: never
  query?: never
  url: '/api/profile'
}

export type ProfileControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerUpdateResponse =
  ProfileControllerUpdateResponses[keyof ProfileControllerUpdateResponses]

export type PostControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts'
}

export type PostControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostDto>
  }
}

export type PostControllerFindAllResponse =
  PostControllerFindAllResponses[keyof PostControllerFindAllResponses]

export type PostControllerCreateData = {
  body: CreatePostDto
  path?: never
  query?: never
  url: '/api/posts'
}

export type PostControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerCreateResponse =
  PostControllerCreateResponses[keyof PostControllerCreateResponses]

export type PostControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerRemoveResponses = {
  204: void
}

export type PostControllerRemoveResponse =
  PostControllerRemoveResponses[keyof PostControllerRemoveResponses]

export type PostControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerFindOneResponse =
  PostControllerFindOneResponses[keyof PostControllerFindOneResponses]

export type PostControllerUpdateData = {
  body: UpdatePostDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerUpdateResponse =
  PostControllerUpdateResponses[keyof PostControllerUpdateResponses]

export type UploadControllerUploadAvatarData = {
  body: CreateUploadAvatarDto
  path?: never
  query?: never
  url: '/api/upload/avatar'
}

export type UploadControllerUploadAvatarResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UploadControllerUploadAvatarResponse =
  UploadControllerUploadAvatarResponses[keyof UploadControllerUploadAvatarResponses]
