// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string
}

export type ProfileDto = {
  id: number
  fullName: string
  avatarUrl: string | null
  birthDay: string | null
  phone: string | null
  biography: string | null
  createdAt: string
  updatedAt: string
}

export type UserResponseDto = {
  id: number
  username: string
  email: string
  activationLink: string | null
  isActivated: boolean
  createdAt: string
  updatedAt: string
  activatedAt: string | null
  profile: ProfileDto
}

export type LoginResponseDto = {
  user: UserResponseDto
  accessToken: string
}

export type BaseResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
}

export type CreateUserDto = {
  email: string
  username: string
  fullName: string
  password: string
}

export type LoginRequestDto = {
  email: string
  password: string
}

export type EmptyResponseDto = {
  [key: string]: unknown
}

export type RefreshResponseDto = {
  accessToken: string
}

export type UpdateProfileDto = {
  fullName?: string
  avatarUrl?: string | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
}

export type PostDto = {
  id: number
  content: string
  createdAt: string
  updatedAt: string
}

export type MessageDto = {
  id: number
  content: string | null
  createdAt: string
  readAt: string | null
}

export type PostLikeDto = {
  id: number
  createdAt: string
}

export type PostCommentDto = {
  id: number
  content: string
  createdAt: string
}

export type SubscriptionDto = {
  id: number
  createdAt: string
}

export type UserResponseWithRelationsDto = {
  id: number
  username: string
  email: string
  activationLink: string | null
  isActivated: boolean
  profile?: UpdateProfileDto
  posts?: Array<PostDto>
  sentMessages?: Array<MessageDto>
  receivedMessages?: Array<MessageDto>
  likesOnPosts?: Array<PostLikeDto>
  comments?: Array<PostCommentDto>
  following?: Array<SubscriptionDto>
  followers?: Array<SubscriptionDto>
  createdAt: string
  updatedAt: string
  activatedAt: string | null
}

export type PaginatedResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
  total: number
  page: number
  pageSize: number
  totalPages: number
  nextPage: number
  prevPage: number
}

export type UpdateUserDto = {
  email?: string
  username?: string
  fullName?: string
}

export type ChangePasswordDto = {
  oldPassword: string
  newPassword: string
}

export type PostFileDto = {
  id: number
  url: string
  type: string | null
  uploadedAt: string
}

export type PostResponseDto = {
  id: number
  content: string
  createdAt: string
  updatedAt: string
  user: UserResponseDto
  files?: Array<PostFileDto>
  likes?: Array<PostLikeDto>
  comments?: Array<PostCommentDto>
}

export type CreatePostDto = {
  content: string
}

export type UpdatePostDto = {
  content?: string
}

export type UploadAvatarPayload = {
  file: Blob | File
}

export type AuthControllerRegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/api/auth/register'
}

export type AuthControllerRegisterResponses = {
  200: BaseResponseDto & {
    data?: LoginResponseDto
  }
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: LoginRequestDto
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type AuthControllerLoginResponses = {
  200: BaseResponseDto & {
    data?: LoginResponseDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/logout'
}

export type AuthControllerLogoutResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses]

export type AuthControllerRefreshData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/refresh'
}

export type AuthControllerRefreshResponses = {
  200: BaseResponseDto & {
    data?: RefreshResponseDto
  }
}

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses]

export type UserControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/users'
}

export type UserControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<UserResponseWithRelationsDto>
  }
}

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses]

export type UserControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerRemoveResponses = {
  204: void
}

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses]

export type UserControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: UserResponseWithRelationsDto
  }
}

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses]

export type UserControllerUpdateData = {
  body: UpdateUserDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: UserResponseWithRelationsDto
  }
}

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses]

export type UserControllerFindOneMinifiedData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/minified/{id}'
}

export type UserControllerFindOneMinifiedResponses = {
  200: BaseResponseDto & {
    data?: UserResponseDto
  }
}

export type UserControllerFindOneMinifiedResponse =
  UserControllerFindOneMinifiedResponses[keyof UserControllerFindOneMinifiedResponses]

export type UserControllerChangePasswordData = {
  body: ChangePasswordDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}/change-password'
}

export type UserControllerChangePasswordResponses = {
  200: BaseResponseDto & {
    data?: UserResponseWithRelationsDto
  }
}

export type UserControllerChangePasswordResponse =
  UserControllerChangePasswordResponses[keyof UserControllerChangePasswordResponses]

export type ProfileControllerMeData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me'
}

export type ProfileControllerMeResponses = {
  200: BaseResponseDto & {
    data?: UserResponseWithRelationsDto
  }
}

export type ProfileControllerMeResponse =
  ProfileControllerMeResponses[keyof ProfileControllerMeResponses]

export type ProfileControllerUpdateData = {
  body: UpdateProfileDto
  path?: never
  query?: never
  url: '/api/profile'
}

export type ProfileControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: UpdateProfileDto
  }
}

export type ProfileControllerUpdateResponse =
  ProfileControllerUpdateResponses[keyof ProfileControllerUpdateResponses]

export type PostControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts'
}

export type PostControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<PostResponseDto>
  }
}

export type PostControllerFindAllResponse =
  PostControllerFindAllResponses[keyof PostControllerFindAllResponses]

export type PostControllerCreateData = {
  body: CreatePostDto
  path?: never
  query?: never
  url: '/api/posts'
}

export type PostControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: PostResponseDto
  }
}

export type PostControllerCreateResponse =
  PostControllerCreateResponses[keyof PostControllerCreateResponses]

export type PostControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerRemoveResponses = {
  204: void
}

export type PostControllerRemoveResponse =
  PostControllerRemoveResponses[keyof PostControllerRemoveResponses]

export type PostControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: PostResponseDto
  }
}

export type PostControllerFindOneResponse =
  PostControllerFindOneResponses[keyof PostControllerFindOneResponses]

export type PostControllerUpdateData = {
  body: UpdatePostDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: PostResponseDto
  }
}

export type PostControllerUpdateResponse =
  PostControllerUpdateResponses[keyof PostControllerUpdateResponses]

export type UploadControllerUploadAvatarData = {
  body: UploadAvatarPayload
  path?: never
  query?: never
  url: '/api/upload/avatar'
}

export type UploadControllerUploadAvatarResponses = {
  200: BaseResponseDto & {
    data?: UserResponseDto
  }
}

export type UploadControllerUploadAvatarResponse =
  UploadControllerUploadAvatarResponses[keyof UploadControllerUploadAvatarResponses]
