// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string
}

export type ResponseFileDto = {
  readonly id: number
  url: string
  type?: string | null
  readonly uploadedAt: string
}

export type ResponseProfileDto = {
  readonly id: number
  fullName: string
  avatar?: ResponseFileDto | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
  readonly createdAt: string
}

export type ResponseUserDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  readonly followersCount: number
  readonly followingCount: number
  readonly isFollowing: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
}

export type ResponseRegisterDto = {
  user: ResponseUserDto
  accessToken: string
}

export type BaseResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
}

export type CreateUserDto = {
  email: string
  username: string
  fullName: string
  password: string
}

export type ResponseLoginDto = {
  user: ResponseUserDto
  accessToken: string
}

export type CreateLoginDto = {
  email: string
  password: string
}

export type EmptyResponseDto = {
  [key: string]: unknown
}

export type ResponseRefreshDto = {
  readonly accessToken: string
}

export type PaginatedResponseDto = {
  message: string
  data: {
    [key: string]: unknown
  }
  total: number
  page: number
  pageSize: number
  totalPages: number
  nextPage: number
  prevPage: number
}

export type UpdateUserDto = {
  email?: string
  username?: string
}

export type CreateChangePasswordDto = {
  oldPassword: string
  newPassword: string
}

export type ResponseProfileDetailedDto = {
  user: ResponseUserDto
}

export type UpdateProfileDto = {
  phone?: string | null
  biography?: string | null
  fullName?: string
  avatar?: number | null
  birthDay?: string | null
}

export type ResponseUserProfileDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
}

export type ResponsePostFileDto = {
  file: ResponseFileDto
}

export type ResponsePostDto = {
  readonly id: number
  content: string
  isLiked: boolean
  user: ResponseUserProfileDto
  files?: Array<ResponsePostFileDto> | null
  likesCount: number
  commentsCount: number
  readonly createdAt: string
  readonly updatedAt: string
}

export type ResponsePostCommentDto = {
  readonly id: number
  user: ResponseUserProfileDto
  content: string
  readonly createdAt: string
  readonly updatedAt: string
}

export type ResponseUserProfileIsFollowingDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
  readonly isFollowing: boolean
}

export type ResponsePostLikeDto = {
  readonly id: number
  user: ResponseUserProfileIsFollowingDto
  readonly createdAt: string
}

export type CreatePostDto = {
  content: string
  files: Array<number>
}

export type CreatePostCommentDto = {
  content: string
}

export type UpdatePostDto = {
  content?: string
  files?: Array<number>
}

export type ResponseUploadDto = {
  readonly id: number
  secure_url: string
  type: string
}

export type CreateUploadDto = {
  file: Blob | File
  folder?: string | null
}

export type ResponseMessageDto = {
  readonly id: number
  readonly senderId: number
  receiverId: number
  conversationId: number
  content?: string | null
  files?: Array<ResponseFileDto> | null
  readonly createdAt: string
}

export type CreateMessageDto = {
  receiverId: number
  conversationId: number
  content?: string | null
  fileIds?: Array<number> | null
}

export type UpdateMessageDto = {
  conversationId?: number
  content?: string | null
  fileIds?: Array<number> | null
}

export type ResponseSubscriptionDto = {
  readonly id: number
  user: ResponseUserProfileDto
  readonly createdAt: string
}

export type ResponseSubscriptionCountDto = {
  followers: number
  following: number
}

export type ResponseConversationDto = {
  readonly id: number
  receiver: ResponseUserProfileDto
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreateConversationDto = {
  receiverId: number
}

export type ResponseFileDtoWritable = {
  url: string
  type?: string | null
}

export type ResponseProfileDtoWritable = {
  fullName: string
  avatar?: ResponseFileDtoWritable | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
}

export type ResponseUserDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type EmptyResponseDtoWritable = {
  [key: string]: unknown
}

export type ResponseUserProfileDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type ResponsePostDtoWritable = {
  content: string
  isLiked: boolean
  user: ResponseUserProfileDtoWritable
  files?: Array<ResponsePostFileDto> | null
  likesCount: number
  commentsCount: number
}

export type ResponsePostCommentDtoWritable = {
  user: ResponseUserProfileDtoWritable
  content: string
}

export type ResponseUserProfileIsFollowingDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type ResponsePostLikeDtoWritable = {
  user: ResponseUserProfileIsFollowingDtoWritable
}

export type ResponseUploadDtoWritable = {
  secure_url: string
  type: string
}

export type ResponseMessageDtoWritable = {
  receiverId: number
  conversationId: number
  content?: string | null
  files?: Array<ResponseFileDtoWritable> | null
}

export type ResponseSubscriptionDtoWritable = {
  user: ResponseUserProfileDtoWritable
}

export type ResponseConversationDtoWritable = {
  receiver: ResponseUserProfileDtoWritable
}

export type AuthControllerRegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/api/auth/register'
}

export type AuthControllerRegisterResponses = {
  200: BaseResponseDto & {
    data?: ResponseRegisterDto
  }
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: CreateLoginDto
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type AuthControllerLoginResponses = {
  200: BaseResponseDto & {
    data?: ResponseLoginDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/logout'
}

export type AuthControllerLogoutResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses]

export type AuthControllerRefreshData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/refresh'
}

export type AuthControllerRefreshResponses = {
  200: BaseResponseDto & {
    data?: ResponseRefreshDto
  }
}

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses]

export type UserControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/users'
}

export type UserControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseUserDto>
  }
}

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses]

export type UserControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerRemoveResponses = {
  204: void
}

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses]

export type UserControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses]

export type UserControllerUpdateData = {
  body: UpdateUserDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses]

export type UserControllerChangePasswordData = {
  body: CreateChangePasswordDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}/change-password'
}

export type UserControllerChangePasswordResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type UserControllerChangePasswordResponse =
  UserControllerChangePasswordResponses[keyof UserControllerChangePasswordResponses]

export type ProfileControllerMeData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me'
}

export type ProfileControllerMeResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerMeResponse =
  ProfileControllerMeResponses[keyof ProfileControllerMeResponses]

export type ProfileControllerMeDetailedData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me/detailed'
}

export type ProfileControllerMeDetailedResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDetailedDto
  }
}

export type ProfileControllerMeDetailedResponse =
  ProfileControllerMeDetailedResponses[keyof ProfileControllerMeDetailedResponses]

export type ProfileControllerUpdateData = {
  body: UpdateProfileDto
  path?: never
  query?: never
  url: '/api/profile'
}

export type ProfileControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerUpdateResponse =
  ProfileControllerUpdateResponses[keyof ProfileControllerUpdateResponses]

export type PostControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts'
}

export type PostControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostDto>
  }
}

export type PostControllerFindAllResponse =
  PostControllerFindAllResponses[keyof PostControllerFindAllResponses]

export type PostControllerCreateData = {
  body: CreatePostDto
  path?: never
  query?: never
  url: '/api/posts'
}

export type PostControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerCreateResponse =
  PostControllerCreateResponses[keyof PostControllerCreateResponses]

export type PostControllerFindAllCommentsData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts/{id}/comments'
}

export type PostControllerFindAllCommentsResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostCommentDto>
  }
}

export type PostControllerFindAllCommentsResponse =
  PostControllerFindAllCommentsResponses[keyof PostControllerFindAllCommentsResponses]

export type PostControllerCreateCommentData = {
  body: CreatePostCommentDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/comments'
}

export type PostControllerCreateCommentResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostControllerCreateCommentResponse =
  PostControllerCreateCommentResponses[keyof PostControllerCreateCommentResponses]

export type PostControllerRemoveLikeData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/likes'
}

export type PostControllerRemoveLikeResponses = {
  204: void
}

export type PostControllerRemoveLikeResponse =
  PostControllerRemoveLikeResponses[keyof PostControllerRemoveLikeResponses]

export type PostControllerFindAllLikesData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts/{id}/likes'
}

export type PostControllerFindAllLikesResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostLikeDto>
  }
}

export type PostControllerFindAllLikesResponse =
  PostControllerFindAllLikesResponses[keyof PostControllerFindAllLikesResponses]

export type PostControllerCreateLikeData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/likes'
}

export type PostControllerCreateLikeResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostControllerCreateLikeResponse =
  PostControllerCreateLikeResponses[keyof PostControllerCreateLikeResponses]

export type PostControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerRemoveResponses = {
  204: void
}

export type PostControllerRemoveResponse =
  PostControllerRemoveResponses[keyof PostControllerRemoveResponses]

export type PostControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerFindOneResponse =
  PostControllerFindOneResponses[keyof PostControllerFindOneResponses]

export type PostControllerUpdateData = {
  body: UpdatePostDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostControllerUpdateResponse =
  PostControllerUpdateResponses[keyof PostControllerUpdateResponses]

export type PostControllerRemoveCommentData = {
  body?: never
  path: {
    id: string
    commentId: string
  }
  query?: never
  url: '/api/posts/{id}/comments/{commentId}'
}

export type PostControllerRemoveCommentResponses = {
  204: void
}

export type PostControllerRemoveCommentResponse =
  PostControllerRemoveCommentResponses[keyof PostControllerRemoveCommentResponses]

export type PostControllerUpdateCommentData = {
  body: CreatePostCommentDto
  path: {
    id: string
    commentId: string
  }
  query?: never
  url: '/api/posts/{id}/comments/{commentId}'
}

export type PostControllerUpdateCommentResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostControllerUpdateCommentResponse =
  PostControllerUpdateCommentResponses[keyof PostControllerUpdateCommentResponses]

export type UploadControllerUploadData = {
  body: CreateUploadDto
  path?: never
  query?: never
  url: '/api/upload'
}

export type UploadControllerUploadResponses = {
  200: BaseResponseDto & {
    data?: ResponseUploadDto
  }
}

export type UploadControllerUploadResponse =
  UploadControllerUploadResponses[keyof UploadControllerUploadResponses]

export type UploadControllerDeleteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/upload/{id}'
}

export type UploadControllerDeleteResponses = {
  204: void
}

export type UploadControllerDeleteResponse =
  UploadControllerDeleteResponses[keyof UploadControllerDeleteResponses]

export type MessageControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/messages/{id}'
}

export type MessageControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerFindOneResponse =
  MessageControllerFindOneResponses[keyof MessageControllerFindOneResponses]

export type MessageControllerUpdateData = {
  body: UpdateMessageDto
  path: {
    id: string
  }
  query?: never
  url: '/api/messages/{id}'
}

export type MessageControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerUpdateResponse =
  MessageControllerUpdateResponses[keyof MessageControllerUpdateResponses]

export type MessageControllerCreateData = {
  body: CreateMessageDto
  path?: never
  query?: never
  url: '/api/messages'
}

export type MessageControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerCreateResponse =
  MessageControllerCreateResponses[keyof MessageControllerCreateResponses]

export type SubscriptionControllerFindAllFollowersData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/subscription/followers/{id}'
}

export type SubscriptionControllerFindAllFollowersResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseSubscriptionDto>
  }
}

export type SubscriptionControllerFindAllFollowersResponse =
  SubscriptionControllerFindAllFollowersResponses[keyof SubscriptionControllerFindAllFollowersResponses]

export type SubscriptionControllerFindAllFollowingData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/subscription/following/{id}'
}

export type SubscriptionControllerFindAllFollowingResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseSubscriptionDto>
  }
}

export type SubscriptionControllerFindAllFollowingResponse =
  SubscriptionControllerFindAllFollowingResponses[keyof SubscriptionControllerFindAllFollowingResponses]

export type SubscriptionControllerFindOneCountData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/count/{id}'
}

export type SubscriptionControllerFindOneCountResponses = {
  200: BaseResponseDto & {
    data?: ResponseSubscriptionCountDto
  }
}

export type SubscriptionControllerFindOneCountResponse =
  SubscriptionControllerFindOneCountResponses[keyof SubscriptionControllerFindOneCountResponses]

export type SubscriptionControllerFollowData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/follow/{id}'
}

export type SubscriptionControllerFollowResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type SubscriptionControllerFollowResponse =
  SubscriptionControllerFollowResponses[keyof SubscriptionControllerFollowResponses]

export type SubscriptionControllerUnfollowData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/unfollow/{id}'
}

export type SubscriptionControllerUnfollowResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type SubscriptionControllerUnfollowResponse =
  SubscriptionControllerUnfollowResponses[keyof SubscriptionControllerUnfollowResponses]

export type ConversationControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/conversations'
}

export type ConversationControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseConversationDto>
  }
}

export type ConversationControllerFindAllResponse =
  ConversationControllerFindAllResponses[keyof ConversationControllerFindAllResponses]

export type ConversationControllerCreateData = {
  body: CreateConversationDto
  path?: never
  query?: never
  url: '/api/conversations'
}

export type ConversationControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponseConversationDto
  }
}

export type ConversationControllerCreateResponse =
  ConversationControllerCreateResponses[keyof ConversationControllerCreateResponses]

export type ConversationControllerFindAllConversationMessagesData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page.
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/conversations/{id}/messages'
}

export type ConversationControllerFindAllConversationMessagesResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseMessageDto>
  }
}

export type ConversationControllerFindAllConversationMessagesResponse =
  ConversationControllerFindAllConversationMessagesResponses[keyof ConversationControllerFindAllConversationMessagesResponses]

export type ConversationControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/conversations/{id}'
}

export type ConversationControllerRemoveResponses = {
  204: void
}

export type ConversationControllerRemoveResponse =
  ConversationControllerRemoveResponses[keyof ConversationControllerRemoveResponses]

export type ConversationControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/conversations/{id}'
}

export type ConversationControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseConversationDto
  }
}

export type ConversationControllerFindOneResponse =
  ConversationControllerFindOneResponses[keyof ConversationControllerFindOneResponses]
