// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions
} from '@tanstack/react-query'
import type { AxiosError } from 'axios'

import { client } from '../client.gen'
import {
  authControllerLogin,
  authControllerLogout,
  authControllerRefresh,
  authControllerRegister,
  conversationControllerCreate,
  conversationControllerFindAll,
  conversationControllerFindAllConversationMessages,
  conversationControllerFindAllSuggestions,
  conversationControllerFindOne,
  conversationControllerFindOneByUserId,
  conversationControllerRemove,
  messageControllerCreate,
  messageControllerFindOne,
  messageControllerRemove,
  messageControllerUpdate,
  type Options,
  postCommentsControllerCreateComment,
  postCommentsControllerFindAllComments,
  postCommentsControllerRemoveComment,
  postCommentsControllerUpdateComment,
  postLikesControllerCreateLike,
  postLikesControllerFindAllLikes,
  postLikesControllerRemoveLike,
  postsControllerCreate,
  postsControllerFindAll,
  postsControllerFindAllMy,
  postsControllerFindOne,
  postsControllerRemove,
  postsControllerUpdate,
  postWsConversationsEventConversationDeleted,
  postWsConversationsEventConversationNew,
  postWsMessagesEventMessageDeleted,
  postWsMessagesEventMessageNew,
  postWsMessagesEventMessageSent,
  postWsMessagesEventMessageUpdated,
  postWsMessagesMessageDelete,
  postWsMessagesMessageSend,
  postWsMessagesMessageUpdate,
  postWsUsersEventUserOffline,
  postWsUsersEventUserOnline,
  postWsUsersEventUserOnlineList,
  postWsUsersUserOnlineListRequest,
  profileControllerMe,
  profileControllerMeDetailed,
  profileControllerUpdate,
  storyControllerCreate,
  storyControllerFindAll,
  storyControllerFindAllByUserId,
  storyControllerFindAllViewers,
  storyControllerFindOne,
  storyControllerRemove,
  storyControllerUpdate,
  subscriptionControllerFindAllFollowers,
  subscriptionControllerFindAllFollowing,
  subscriptionControllerFindOneCount,
  subscriptionControllerFollow,
  subscriptionControllerRemoveFollower,
  subscriptionControllerUnfollow,
  uploadControllerDelete,
  uploadControllerUpload,
  userControllerChangePassword,
  userControllerFindAll,
  userControllerFindOne,
  userControllerRemove,
  userControllerUpdate
} from '../sdk.gen'
import type {
  AuthControllerLoginData,
  AuthControllerLoginResponse,
  AuthControllerLogoutData,
  AuthControllerLogoutResponse,
  AuthControllerRefreshData,
  AuthControllerRefreshResponse,
  AuthControllerRegisterData,
  AuthControllerRegisterResponse,
  ConversationControllerCreateData,
  ConversationControllerCreateResponse,
  ConversationControllerFindAllConversationMessagesData,
  ConversationControllerFindAllConversationMessagesResponse,
  ConversationControllerFindAllData,
  ConversationControllerFindAllResponse,
  ConversationControllerFindAllSuggestionsData,
  ConversationControllerFindAllSuggestionsResponse,
  ConversationControllerFindOneByUserIdData,
  ConversationControllerFindOneByUserIdResponse,
  ConversationControllerFindOneData,
  ConversationControllerFindOneResponse,
  ConversationControllerRemoveData,
  ConversationControllerRemoveResponse,
  MessageControllerCreateData,
  MessageControllerCreateResponse,
  MessageControllerFindOneData,
  MessageControllerFindOneResponse,
  MessageControllerRemoveData,
  MessageControllerRemoveResponse,
  MessageControllerUpdateData,
  MessageControllerUpdateResponse,
  PostCommentsControllerCreateCommentData,
  PostCommentsControllerCreateCommentResponse,
  PostCommentsControllerFindAllCommentsData,
  PostCommentsControllerFindAllCommentsResponse,
  PostCommentsControllerRemoveCommentData,
  PostCommentsControllerRemoveCommentResponse,
  PostCommentsControllerUpdateCommentData,
  PostCommentsControllerUpdateCommentResponse,
  PostLikesControllerCreateLikeData,
  PostLikesControllerCreateLikeResponse,
  PostLikesControllerFindAllLikesData,
  PostLikesControllerFindAllLikesResponse,
  PostLikesControllerRemoveLikeData,
  PostLikesControllerRemoveLikeResponse,
  PostsControllerCreateData,
  PostsControllerCreateResponse,
  PostsControllerFindAllData,
  PostsControllerFindAllMyData,
  PostsControllerFindAllMyResponse,
  PostsControllerFindAllResponse,
  PostsControllerFindOneData,
  PostsControllerFindOneResponse,
  PostsControllerRemoveData,
  PostsControllerRemoveResponse,
  PostsControllerUpdateData,
  PostsControllerUpdateResponse,
  PostWsConversationsEventConversationDeletedData,
  PostWsConversationsEventConversationDeletedResponse,
  PostWsConversationsEventConversationNewData,
  PostWsConversationsEventConversationNewResponse,
  PostWsMessagesEventMessageDeletedData,
  PostWsMessagesEventMessageDeletedResponse,
  PostWsMessagesEventMessageNewData,
  PostWsMessagesEventMessageNewResponse,
  PostWsMessagesEventMessageSentData,
  PostWsMessagesEventMessageSentResponse,
  PostWsMessagesEventMessageUpdatedData,
  PostWsMessagesEventMessageUpdatedResponse,
  PostWsMessagesMessageDeleteData,
  PostWsMessagesMessageDeleteResponse,
  PostWsMessagesMessageSendData,
  PostWsMessagesMessageSendResponse,
  PostWsMessagesMessageUpdateData,
  PostWsMessagesMessageUpdateResponse,
  PostWsUsersEventUserOfflineData,
  PostWsUsersEventUserOfflineResponse,
  PostWsUsersEventUserOnlineData,
  PostWsUsersEventUserOnlineListData,
  PostWsUsersEventUserOnlineListResponse,
  PostWsUsersEventUserOnlineResponse,
  PostWsUsersUserOnlineListRequestData,
  PostWsUsersUserOnlineListRequestResponse,
  ProfileControllerMeData,
  ProfileControllerMeDetailedData,
  ProfileControllerMeDetailedResponse,
  ProfileControllerMeResponse,
  ProfileControllerUpdateData,
  ProfileControllerUpdateResponse,
  StoryControllerCreateData,
  StoryControllerCreateResponse,
  StoryControllerFindAllByUserIdData,
  StoryControllerFindAllByUserIdResponse,
  StoryControllerFindAllData,
  StoryControllerFindAllResponse,
  StoryControllerFindAllViewersData,
  StoryControllerFindAllViewersResponse,
  StoryControllerFindOneData,
  StoryControllerFindOneResponse,
  StoryControllerRemoveData,
  StoryControllerRemoveResponse,
  StoryControllerUpdateData,
  StoryControllerUpdateResponse,
  SubscriptionControllerFindAllFollowersData,
  SubscriptionControllerFindAllFollowersResponse,
  SubscriptionControllerFindAllFollowingData,
  SubscriptionControllerFindAllFollowingResponse,
  SubscriptionControllerFindOneCountData,
  SubscriptionControllerFindOneCountResponse,
  SubscriptionControllerFollowData,
  SubscriptionControllerFollowResponse,
  SubscriptionControllerRemoveFollowerData,
  SubscriptionControllerRemoveFollowerResponse,
  SubscriptionControllerUnfollowData,
  SubscriptionControllerUnfollowResponse,
  UploadControllerDeleteData,
  UploadControllerDeleteResponse,
  UploadControllerUploadData,
  UploadControllerUploadResponse,
  UserControllerChangePasswordData,
  UserControllerChangePasswordResponse,
  UserControllerFindAllData,
  UserControllerFindAllResponse,
  UserControllerFindOneData,
  UserControllerFindOneResponse,
  UserControllerRemoveData,
  UserControllerRemoveResponse,
  UserControllerUpdateData,
  UserControllerUpdateResponse
} from '../types.gen'

/**
 * Validation pattern for password:
 * `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$/`
 */
export const authControllerRegisterMutation = (
  options?: Partial<Options<AuthControllerRegisterData>>
): UseMutationOptions<
  AuthControllerRegisterResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRegisterResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRegister({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const authControllerLoginMutation = (
  options?: Partial<Options<AuthControllerLoginData>>
): UseMutationOptions<
  AuthControllerLoginResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLoginResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogin({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const authControllerLogoutMutation = (
  options?: Partial<Options<AuthControllerLogoutData>>
): UseMutationOptions<
  AuthControllerLogoutResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerLogoutResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerLogout({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const authControllerRefreshMutation = (
  options?: Partial<Options<AuthControllerRefreshData>>
): UseMutationOptions<
  AuthControllerRefreshResponse,
  AxiosError<DefaultError>,
  Options<AuthControllerRefreshData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthControllerRefreshResponse,
    AxiosError<DefaultError>,
    Options<AuthControllerRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authControllerRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const userControllerFindAllQueryKey = (
  options?: Options<UserControllerFindAllData>
) => createQueryKey('userControllerFindAll', options)

export const userControllerFindAllOptions = (
  options?: Options<UserControllerFindAllData>
) =>
  queryOptions<
    UserControllerFindAllResponse,
    AxiosError<DefaultError>,
    UserControllerFindAllResponse,
    ReturnType<typeof userControllerFindAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: userControllerFindAllQueryKey(options)
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any)
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any)
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any)
    }
  }
  return params as unknown as typeof page
}

export const userControllerFindAllInfiniteQueryKey = (
  options?: Options<UserControllerFindAllData>
): QueryKey<Options<UserControllerFindAllData>> =>
  createQueryKey('userControllerFindAll', options, true)

export const userControllerFindAllInfiniteOptions = (
  options?: Options<UserControllerFindAllData>
) =>
  infiniteQueryOptions<
    UserControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<UserControllerFindAllResponse>,
    QueryKey<Options<UserControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<UserControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<UserControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await userControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: userControllerFindAllInfiniteQueryKey(options)
    }
  )

export const userControllerRemoveMutation = (
  options?: Partial<Options<UserControllerRemoveData>>
): UseMutationOptions<
  UserControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<UserControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<UserControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const userControllerFindOneQueryKey = (
  options: Options<UserControllerFindOneData>
) => createQueryKey('userControllerFindOne', options)

export const userControllerFindOneOptions = (
  options: Options<UserControllerFindOneData>
) =>
  queryOptions<
    UserControllerFindOneResponse,
    AxiosError<DefaultError>,
    UserControllerFindOneResponse,
    ReturnType<typeof userControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: userControllerFindOneQueryKey(options)
  })

export const userControllerUpdateMutation = (
  options?: Partial<Options<UserControllerUpdateData>>
): UseMutationOptions<
  UserControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<UserControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<UserControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const userControllerChangePasswordMutation = (
  options?: Partial<Options<UserControllerChangePasswordData>>
): UseMutationOptions<
  UserControllerChangePasswordResponse,
  AxiosError<DefaultError>,
  Options<UserControllerChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    UserControllerChangePasswordResponse,
    AxiosError<DefaultError>,
    Options<UserControllerChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userControllerChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const profileControllerMeQueryKey = (
  options?: Options<ProfileControllerMeData>
) => createQueryKey('profileControllerMe', options)

export const profileControllerMeOptions = (
  options?: Options<ProfileControllerMeData>
) =>
  queryOptions<
    ProfileControllerMeResponse,
    AxiosError<DefaultError>,
    ProfileControllerMeResponse,
    ReturnType<typeof profileControllerMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await profileControllerMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: profileControllerMeQueryKey(options)
  })

export const profileControllerMeDetailedQueryKey = (
  options?: Options<ProfileControllerMeDetailedData>
) => createQueryKey('profileControllerMeDetailed', options)

export const profileControllerMeDetailedOptions = (
  options?: Options<ProfileControllerMeDetailedData>
) =>
  queryOptions<
    ProfileControllerMeDetailedResponse,
    AxiosError<DefaultError>,
    ProfileControllerMeDetailedResponse,
    ReturnType<typeof profileControllerMeDetailedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await profileControllerMeDetailed({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: profileControllerMeDetailedQueryKey(options)
  })

export const profileControllerUpdateMutation = (
  options?: Partial<Options<ProfileControllerUpdateData>>
): UseMutationOptions<
  ProfileControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<ProfileControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    ProfileControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<ProfileControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await profileControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postsControllerFindAllQueryKey = (
  options?: Options<PostsControllerFindAllData>
) => createQueryKey('postsControllerFindAll', options)

export const postsControllerFindAllOptions = (
  options?: Options<PostsControllerFindAllData>
) =>
  queryOptions<
    PostsControllerFindAllResponse,
    AxiosError<DefaultError>,
    PostsControllerFindAllResponse,
    ReturnType<typeof postsControllerFindAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postsControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: postsControllerFindAllQueryKey(options)
  })

export const postsControllerFindAllInfiniteQueryKey = (
  options?: Options<PostsControllerFindAllData>
): QueryKey<Options<PostsControllerFindAllData>> =>
  createQueryKey('postsControllerFindAll', options, true)

export const postsControllerFindAllInfiniteOptions = (
  options?: Options<PostsControllerFindAllData>
) =>
  infiniteQueryOptions<
    PostsControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostsControllerFindAllResponse>,
    QueryKey<Options<PostsControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<PostsControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostsControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postsControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: postsControllerFindAllInfiniteQueryKey(options)
    }
  )

export const postsControllerCreateMutation = (
  options?: Partial<Options<PostsControllerCreateData>>
): UseMutationOptions<
  PostsControllerCreateResponse,
  AxiosError<DefaultError>,
  Options<PostsControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostsControllerCreateResponse,
    AxiosError<DefaultError>,
    Options<PostsControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postsControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postsControllerFindAllMyQueryKey = (
  options?: Options<PostsControllerFindAllMyData>
) => createQueryKey('postsControllerFindAllMy', options)

export const postsControllerFindAllMyOptions = (
  options?: Options<PostsControllerFindAllMyData>
) =>
  queryOptions<
    PostsControllerFindAllMyResponse,
    AxiosError<DefaultError>,
    PostsControllerFindAllMyResponse,
    ReturnType<typeof postsControllerFindAllMyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postsControllerFindAllMy({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: postsControllerFindAllMyQueryKey(options)
  })

export const postsControllerFindAllMyInfiniteQueryKey = (
  options?: Options<PostsControllerFindAllMyData>
): QueryKey<Options<PostsControllerFindAllMyData>> =>
  createQueryKey('postsControllerFindAllMy', options, true)

export const postsControllerFindAllMyInfiniteOptions = (
  options?: Options<PostsControllerFindAllMyData>
) =>
  infiniteQueryOptions<
    PostsControllerFindAllMyResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostsControllerFindAllMyResponse>,
    QueryKey<Options<PostsControllerFindAllMyData>>,
    | number
    | Pick<
        QueryKey<Options<PostsControllerFindAllMyData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostsControllerFindAllMyData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postsControllerFindAllMy({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: postsControllerFindAllMyInfiniteQueryKey(options)
    }
  )

export const postsControllerRemoveMutation = (
  options?: Partial<Options<PostsControllerRemoveData>>
): UseMutationOptions<
  PostsControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<PostsControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    PostsControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<PostsControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postsControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postsControllerFindOneQueryKey = (
  options: Options<PostsControllerFindOneData>
) => createQueryKey('postsControllerFindOne', options)

export const postsControllerFindOneOptions = (
  options: Options<PostsControllerFindOneData>
) =>
  queryOptions<
    PostsControllerFindOneResponse,
    AxiosError<DefaultError>,
    PostsControllerFindOneResponse,
    ReturnType<typeof postsControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postsControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: postsControllerFindOneQueryKey(options)
  })

export const postsControllerUpdateMutation = (
  options?: Partial<Options<PostsControllerUpdateData>>
): UseMutationOptions<
  PostsControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<PostsControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostsControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<PostsControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postsControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postCommentsControllerFindAllCommentsQueryKey = (
  options: Options<PostCommentsControllerFindAllCommentsData>
) => createQueryKey('postCommentsControllerFindAllComments', options)

export const postCommentsControllerFindAllCommentsOptions = (
  options: Options<PostCommentsControllerFindAllCommentsData>
) =>
  queryOptions<
    PostCommentsControllerFindAllCommentsResponse,
    AxiosError<DefaultError>,
    PostCommentsControllerFindAllCommentsResponse,
    ReturnType<typeof postCommentsControllerFindAllCommentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postCommentsControllerFindAllComments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: postCommentsControllerFindAllCommentsQueryKey(options)
  })

export const postCommentsControllerFindAllCommentsInfiniteQueryKey = (
  options: Options<PostCommentsControllerFindAllCommentsData>
): QueryKey<Options<PostCommentsControllerFindAllCommentsData>> =>
  createQueryKey('postCommentsControllerFindAllComments', options, true)

export const postCommentsControllerFindAllCommentsInfiniteOptions = (
  options: Options<PostCommentsControllerFindAllCommentsData>
) =>
  infiniteQueryOptions<
    PostCommentsControllerFindAllCommentsResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostCommentsControllerFindAllCommentsResponse>,
    QueryKey<Options<PostCommentsControllerFindAllCommentsData>>,
    | number
    | Pick<
        QueryKey<Options<PostCommentsControllerFindAllCommentsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostCommentsControllerFindAllCommentsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postCommentsControllerFindAllComments({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: postCommentsControllerFindAllCommentsInfiniteQueryKey(options)
    }
  )

export const postCommentsControllerCreateCommentMutation = (
  options?: Partial<Options<PostCommentsControllerCreateCommentData>>
): UseMutationOptions<
  PostCommentsControllerCreateCommentResponse,
  AxiosError<DefaultError>,
  Options<PostCommentsControllerCreateCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostCommentsControllerCreateCommentResponse,
    AxiosError<DefaultError>,
    Options<PostCommentsControllerCreateCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postCommentsControllerCreateComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postCommentsControllerRemoveCommentMutation = (
  options?: Partial<Options<PostCommentsControllerRemoveCommentData>>
): UseMutationOptions<
  PostCommentsControllerRemoveCommentResponse,
  AxiosError<DefaultError>,
  Options<PostCommentsControllerRemoveCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostCommentsControllerRemoveCommentResponse,
    AxiosError<DefaultError>,
    Options<PostCommentsControllerRemoveCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postCommentsControllerRemoveComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postCommentsControllerUpdateCommentMutation = (
  options?: Partial<Options<PostCommentsControllerUpdateCommentData>>
): UseMutationOptions<
  PostCommentsControllerUpdateCommentResponse,
  AxiosError<DefaultError>,
  Options<PostCommentsControllerUpdateCommentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostCommentsControllerUpdateCommentResponse,
    AxiosError<DefaultError>,
    Options<PostCommentsControllerUpdateCommentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postCommentsControllerUpdateComment({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postLikesControllerRemoveLikeMutation = (
  options?: Partial<Options<PostLikesControllerRemoveLikeData>>
): UseMutationOptions<
  PostLikesControllerRemoveLikeResponse,
  AxiosError<DefaultError>,
  Options<PostLikesControllerRemoveLikeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostLikesControllerRemoveLikeResponse,
    AxiosError<DefaultError>,
    Options<PostLikesControllerRemoveLikeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postLikesControllerRemoveLike({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const postLikesControllerFindAllLikesQueryKey = (
  options: Options<PostLikesControllerFindAllLikesData>
) => createQueryKey('postLikesControllerFindAllLikes', options)

export const postLikesControllerFindAllLikesOptions = (
  options: Options<PostLikesControllerFindAllLikesData>
) =>
  queryOptions<
    PostLikesControllerFindAllLikesResponse,
    AxiosError<DefaultError>,
    PostLikesControllerFindAllLikesResponse,
    ReturnType<typeof postLikesControllerFindAllLikesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postLikesControllerFindAllLikes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: postLikesControllerFindAllLikesQueryKey(options)
  })

export const postLikesControllerFindAllLikesInfiniteQueryKey = (
  options: Options<PostLikesControllerFindAllLikesData>
): QueryKey<Options<PostLikesControllerFindAllLikesData>> =>
  createQueryKey('postLikesControllerFindAllLikes', options, true)

export const postLikesControllerFindAllLikesInfiniteOptions = (
  options: Options<PostLikesControllerFindAllLikesData>
) =>
  infiniteQueryOptions<
    PostLikesControllerFindAllLikesResponse,
    AxiosError<DefaultError>,
    InfiniteData<PostLikesControllerFindAllLikesResponse>,
    QueryKey<Options<PostLikesControllerFindAllLikesData>>,
    | number
    | Pick<
        QueryKey<Options<PostLikesControllerFindAllLikesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<PostLikesControllerFindAllLikesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await postLikesControllerFindAllLikes({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: postLikesControllerFindAllLikesInfiniteQueryKey(options)
    }
  )

export const postLikesControllerCreateLikeMutation = (
  options?: Partial<Options<PostLikesControllerCreateLikeData>>
): UseMutationOptions<
  PostLikesControllerCreateLikeResponse,
  AxiosError<DefaultError>,
  Options<PostLikesControllerCreateLikeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostLikesControllerCreateLikeResponse,
    AxiosError<DefaultError>,
    Options<PostLikesControllerCreateLikeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postLikesControllerCreateLike({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const uploadControllerUploadMutation = (
  options?: Partial<Options<UploadControllerUploadData>>
): UseMutationOptions<
  UploadControllerUploadResponse,
  AxiosError<DefaultError>,
  Options<UploadControllerUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadControllerUploadResponse,
    AxiosError<DefaultError>,
    Options<UploadControllerUploadData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadControllerUpload({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const uploadControllerDeleteMutation = (
  options?: Partial<Options<UploadControllerDeleteData>>
): UseMutationOptions<
  UploadControllerDeleteResponse,
  AxiosError<DefaultError>,
  Options<UploadControllerDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadControllerDeleteResponse,
    AxiosError<DefaultError>,
    Options<UploadControllerDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadControllerDelete({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const messageControllerRemoveMutation = (
  options?: Partial<Options<MessageControllerRemoveData>>
): UseMutationOptions<
  MessageControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<MessageControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    MessageControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<MessageControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await messageControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const messageControllerFindOneQueryKey = (
  options: Options<MessageControllerFindOneData>
) => createQueryKey('messageControllerFindOne', options)

export const messageControllerFindOneOptions = (
  options: Options<MessageControllerFindOneData>
) =>
  queryOptions<
    MessageControllerFindOneResponse,
    AxiosError<DefaultError>,
    MessageControllerFindOneResponse,
    ReturnType<typeof messageControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await messageControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: messageControllerFindOneQueryKey(options)
  })

export const messageControllerUpdateMutation = (
  options?: Partial<Options<MessageControllerUpdateData>>
): UseMutationOptions<
  MessageControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<MessageControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    MessageControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<MessageControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await messageControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const messageControllerCreateMutation = (
  options?: Partial<Options<MessageControllerCreateData>>
): UseMutationOptions<
  MessageControllerCreateResponse,
  AxiosError<DefaultError>,
  Options<MessageControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    MessageControllerCreateResponse,
    AxiosError<DefaultError>,
    Options<MessageControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await messageControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const subscriptionControllerFindAllFollowersQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) => createQueryKey('subscriptionControllerFindAllFollowers', options)

export const subscriptionControllerFindAllFollowersOptions = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) =>
  queryOptions<
    SubscriptionControllerFindAllFollowersResponse,
    AxiosError<DefaultError>,
    SubscriptionControllerFindAllFollowersResponse,
    ReturnType<typeof subscriptionControllerFindAllFollowersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindAllFollowers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: subscriptionControllerFindAllFollowersQueryKey(options)
  })

export const subscriptionControllerFindAllFollowersInfiniteQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowersData>
): QueryKey<Options<SubscriptionControllerFindAllFollowersData>> =>
  createQueryKey('subscriptionControllerFindAllFollowers', options, true)

export const subscriptionControllerFindAllFollowersInfiniteOptions = (
  options: Options<SubscriptionControllerFindAllFollowersData>
) =>
  infiniteQueryOptions<
    SubscriptionControllerFindAllFollowersResponse,
    AxiosError<DefaultError>,
    InfiniteData<SubscriptionControllerFindAllFollowersResponse>,
    QueryKey<Options<SubscriptionControllerFindAllFollowersData>>,
    | number
    | Pick<
        QueryKey<Options<SubscriptionControllerFindAllFollowersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubscriptionControllerFindAllFollowersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await subscriptionControllerFindAllFollowers({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: subscriptionControllerFindAllFollowersInfiniteQueryKey(options)
    }
  )

export const subscriptionControllerFindAllFollowingQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) => createQueryKey('subscriptionControllerFindAllFollowing', options)

export const subscriptionControllerFindAllFollowingOptions = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) =>
  queryOptions<
    SubscriptionControllerFindAllFollowingResponse,
    AxiosError<DefaultError>,
    SubscriptionControllerFindAllFollowingResponse,
    ReturnType<typeof subscriptionControllerFindAllFollowingQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindAllFollowing({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: subscriptionControllerFindAllFollowingQueryKey(options)
  })

export const subscriptionControllerFindAllFollowingInfiniteQueryKey = (
  options: Options<SubscriptionControllerFindAllFollowingData>
): QueryKey<Options<SubscriptionControllerFindAllFollowingData>> =>
  createQueryKey('subscriptionControllerFindAllFollowing', options, true)

export const subscriptionControllerFindAllFollowingInfiniteOptions = (
  options: Options<SubscriptionControllerFindAllFollowingData>
) =>
  infiniteQueryOptions<
    SubscriptionControllerFindAllFollowingResponse,
    AxiosError<DefaultError>,
    InfiniteData<SubscriptionControllerFindAllFollowingResponse>,
    QueryKey<Options<SubscriptionControllerFindAllFollowingData>>,
    | number
    | Pick<
        QueryKey<Options<SubscriptionControllerFindAllFollowingData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubscriptionControllerFindAllFollowingData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await subscriptionControllerFindAllFollowing({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: subscriptionControllerFindAllFollowingInfiniteQueryKey(options)
    }
  )

export const subscriptionControllerFindOneCountQueryKey = (
  options: Options<SubscriptionControllerFindOneCountData>
) => createQueryKey('subscriptionControllerFindOneCount', options)

export const subscriptionControllerFindOneCountOptions = (
  options: Options<SubscriptionControllerFindOneCountData>
) =>
  queryOptions<
    SubscriptionControllerFindOneCountResponse,
    AxiosError<DefaultError>,
    SubscriptionControllerFindOneCountResponse,
    ReturnType<typeof subscriptionControllerFindOneCountQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await subscriptionControllerFindOneCount({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: subscriptionControllerFindOneCountQueryKey(options)
  })

export const subscriptionControllerFollowMutation = (
  options?: Partial<Options<SubscriptionControllerFollowData>>
): UseMutationOptions<
  SubscriptionControllerFollowResponse,
  AxiosError<DefaultError>,
  Options<SubscriptionControllerFollowData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscriptionControllerFollowResponse,
    AxiosError<DefaultError>,
    Options<SubscriptionControllerFollowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await subscriptionControllerFollow({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const subscriptionControllerUnfollowMutation = (
  options?: Partial<Options<SubscriptionControllerUnfollowData>>
): UseMutationOptions<
  SubscriptionControllerUnfollowResponse,
  AxiosError<DefaultError>,
  Options<SubscriptionControllerUnfollowData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscriptionControllerUnfollowResponse,
    AxiosError<DefaultError>,
    Options<SubscriptionControllerUnfollowData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await subscriptionControllerUnfollow({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const subscriptionControllerRemoveFollowerMutation = (
  options?: Partial<Options<SubscriptionControllerRemoveFollowerData>>
): UseMutationOptions<
  SubscriptionControllerRemoveFollowerResponse,
  AxiosError<DefaultError>,
  Options<SubscriptionControllerRemoveFollowerData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscriptionControllerRemoveFollowerResponse,
    AxiosError<DefaultError>,
    Options<SubscriptionControllerRemoveFollowerData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await subscriptionControllerRemoveFollower({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const conversationControllerFindAllQueryKey = (
  options?: Options<ConversationControllerFindAllData>
) => createQueryKey('conversationControllerFindAll', options)

export const conversationControllerFindAllOptions = (
  options?: Options<ConversationControllerFindAllData>
) =>
  queryOptions<
    ConversationControllerFindAllResponse,
    AxiosError<DefaultError>,
    ConversationControllerFindAllResponse,
    ReturnType<typeof conversationControllerFindAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await conversationControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: conversationControllerFindAllQueryKey(options)
  })

export const conversationControllerFindAllInfiniteQueryKey = (
  options?: Options<ConversationControllerFindAllData>
): QueryKey<Options<ConversationControllerFindAllData>> =>
  createQueryKey('conversationControllerFindAll', options, true)

export const conversationControllerFindAllInfiniteOptions = (
  options?: Options<ConversationControllerFindAllData>
) =>
  infiniteQueryOptions<
    ConversationControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<ConversationControllerFindAllResponse>,
    QueryKey<Options<ConversationControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<ConversationControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ConversationControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await conversationControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: conversationControllerFindAllInfiniteQueryKey(options)
    }
  )

export const conversationControllerCreateMutation = (
  options?: Partial<Options<ConversationControllerCreateData>>
): UseMutationOptions<
  ConversationControllerCreateResponse,
  AxiosError<DefaultError>,
  Options<ConversationControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    ConversationControllerCreateResponse,
    AxiosError<DefaultError>,
    Options<ConversationControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await conversationControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const conversationControllerFindAllSuggestionsQueryKey = (
  options?: Options<ConversationControllerFindAllSuggestionsData>
) => createQueryKey('conversationControllerFindAllSuggestions', options)

export const conversationControllerFindAllSuggestionsOptions = (
  options?: Options<ConversationControllerFindAllSuggestionsData>
) =>
  queryOptions<
    ConversationControllerFindAllSuggestionsResponse,
    AxiosError<DefaultError>,
    ConversationControllerFindAllSuggestionsResponse,
    ReturnType<typeof conversationControllerFindAllSuggestionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await conversationControllerFindAllSuggestions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: conversationControllerFindAllSuggestionsQueryKey(options)
  })

export const conversationControllerFindAllSuggestionsInfiniteQueryKey = (
  options?: Options<ConversationControllerFindAllSuggestionsData>
): QueryKey<Options<ConversationControllerFindAllSuggestionsData>> =>
  createQueryKey('conversationControllerFindAllSuggestions', options, true)

export const conversationControllerFindAllSuggestionsInfiniteOptions = (
  options?: Options<ConversationControllerFindAllSuggestionsData>
) =>
  infiniteQueryOptions<
    ConversationControllerFindAllSuggestionsResponse,
    AxiosError<DefaultError>,
    InfiniteData<ConversationControllerFindAllSuggestionsResponse>,
    QueryKey<Options<ConversationControllerFindAllSuggestionsData>>,
    | number
    | Pick<
        QueryKey<Options<ConversationControllerFindAllSuggestionsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ConversationControllerFindAllSuggestionsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await conversationControllerFindAllSuggestions({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey:
        conversationControllerFindAllSuggestionsInfiniteQueryKey(options)
    }
  )

export const conversationControllerFindOneByUserIdQueryKey = (
  options: Options<ConversationControllerFindOneByUserIdData>
) => createQueryKey('conversationControllerFindOneByUserId', options)

export const conversationControllerFindOneByUserIdOptions = (
  options: Options<ConversationControllerFindOneByUserIdData>
) =>
  queryOptions<
    ConversationControllerFindOneByUserIdResponse,
    AxiosError<DefaultError>,
    ConversationControllerFindOneByUserIdResponse,
    ReturnType<typeof conversationControllerFindOneByUserIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await conversationControllerFindOneByUserId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: conversationControllerFindOneByUserIdQueryKey(options)
  })

export const conversationControllerFindAllConversationMessagesQueryKey = (
  options: Options<ConversationControllerFindAllConversationMessagesData>
) =>
  createQueryKey('conversationControllerFindAllConversationMessages', options)

export const conversationControllerFindAllConversationMessagesOptions = (
  options: Options<ConversationControllerFindAllConversationMessagesData>
) =>
  queryOptions<
    ConversationControllerFindAllConversationMessagesResponse,
    AxiosError<DefaultError>,
    ConversationControllerFindAllConversationMessagesResponse,
    ReturnType<typeof conversationControllerFindAllConversationMessagesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await conversationControllerFindAllConversationMessages({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: conversationControllerFindAllConversationMessagesQueryKey(options)
  })

export const conversationControllerFindAllConversationMessagesInfiniteQueryKey =
  (
    options: Options<ConversationControllerFindAllConversationMessagesData>
  ): QueryKey<Options<ConversationControllerFindAllConversationMessagesData>> =>
    createQueryKey(
      'conversationControllerFindAllConversationMessages',
      options,
      true
    )

export const conversationControllerFindAllConversationMessagesInfiniteOptions =
  (options: Options<ConversationControllerFindAllConversationMessagesData>) =>
    infiniteQueryOptions<
      ConversationControllerFindAllConversationMessagesResponse,
      AxiosError<DefaultError>,
      InfiniteData<ConversationControllerFindAllConversationMessagesResponse>,
      QueryKey<Options<ConversationControllerFindAllConversationMessagesData>>,
      | number
      | Pick<
          QueryKey<
            Options<ConversationControllerFindAllConversationMessagesData>
          >[0],
          'body' | 'headers' | 'path' | 'query'
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<ConversationControllerFindAllConversationMessagesData>
            >[0],
            'body' | 'headers' | 'path' | 'query'
          > =
            typeof pageParam === 'object'
              ? pageParam
              : {
                  query: {
                    page: pageParam
                  }
                }
          const params = createInfiniteParams(queryKey, page)
          const { data } =
            await conversationControllerFindAllConversationMessages({
              ...options,
              ...params,
              signal,
              throwOnError: true
            })
          return data
        },
        queryKey:
          conversationControllerFindAllConversationMessagesInfiniteQueryKey(
            options
          )
      }
    )

export const conversationControllerRemoveMutation = (
  options?: Partial<Options<ConversationControllerRemoveData>>
): UseMutationOptions<
  ConversationControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<ConversationControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    ConversationControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<ConversationControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await conversationControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const conversationControllerFindOneQueryKey = (
  options: Options<ConversationControllerFindOneData>
) => createQueryKey('conversationControllerFindOne', options)

export const conversationControllerFindOneOptions = (
  options: Options<ConversationControllerFindOneData>
) =>
  queryOptions<
    ConversationControllerFindOneResponse,
    AxiosError<DefaultError>,
    ConversationControllerFindOneResponse,
    ReturnType<typeof conversationControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await conversationControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: conversationControllerFindOneQueryKey(options)
  })

export const storyControllerFindAllQueryKey = (
  options?: Options<StoryControllerFindAllData>
) => createQueryKey('storyControllerFindAll', options)

export const storyControllerFindAllOptions = (
  options?: Options<StoryControllerFindAllData>
) =>
  queryOptions<
    StoryControllerFindAllResponse,
    AxiosError<DefaultError>,
    StoryControllerFindAllResponse,
    ReturnType<typeof storyControllerFindAllQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await storyControllerFindAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: storyControllerFindAllQueryKey(options)
  })

export const storyControllerFindAllInfiniteQueryKey = (
  options?: Options<StoryControllerFindAllData>
): QueryKey<Options<StoryControllerFindAllData>> =>
  createQueryKey('storyControllerFindAll', options, true)

export const storyControllerFindAllInfiniteOptions = (
  options?: Options<StoryControllerFindAllData>
) =>
  infiniteQueryOptions<
    StoryControllerFindAllResponse,
    AxiosError<DefaultError>,
    InfiniteData<StoryControllerFindAllResponse>,
    QueryKey<Options<StoryControllerFindAllData>>,
    | number
    | Pick<
        QueryKey<Options<StoryControllerFindAllData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<StoryControllerFindAllData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await storyControllerFindAll({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: storyControllerFindAllInfiniteQueryKey(options)
    }
  )

export const storyControllerCreateMutation = (
  options?: Partial<Options<StoryControllerCreateData>>
): UseMutationOptions<
  StoryControllerCreateResponse,
  AxiosError<DefaultError>,
  Options<StoryControllerCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    StoryControllerCreateResponse,
    AxiosError<DefaultError>,
    Options<StoryControllerCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await storyControllerCreate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const storyControllerFindAllViewersQueryKey = (
  options: Options<StoryControllerFindAllViewersData>
) => createQueryKey('storyControllerFindAllViewers', options)

export const storyControllerFindAllViewersOptions = (
  options: Options<StoryControllerFindAllViewersData>
) =>
  queryOptions<
    StoryControllerFindAllViewersResponse,
    AxiosError<DefaultError>,
    StoryControllerFindAllViewersResponse,
    ReturnType<typeof storyControllerFindAllViewersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await storyControllerFindAllViewers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: storyControllerFindAllViewersQueryKey(options)
  })

export const storyControllerFindAllViewersInfiniteQueryKey = (
  options: Options<StoryControllerFindAllViewersData>
): QueryKey<Options<StoryControllerFindAllViewersData>> =>
  createQueryKey('storyControllerFindAllViewers', options, true)

export const storyControllerFindAllViewersInfiniteOptions = (
  options: Options<StoryControllerFindAllViewersData>
) =>
  infiniteQueryOptions<
    StoryControllerFindAllViewersResponse,
    AxiosError<DefaultError>,
    InfiniteData<StoryControllerFindAllViewersResponse>,
    QueryKey<Options<StoryControllerFindAllViewersData>>,
    | number
    | Pick<
        QueryKey<Options<StoryControllerFindAllViewersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<StoryControllerFindAllViewersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await storyControllerFindAllViewers({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: storyControllerFindAllViewersInfiniteQueryKey(options)
    }
  )

export const storyControllerFindAllByUserIdQueryKey = (
  options: Options<StoryControllerFindAllByUserIdData>
) => createQueryKey('storyControllerFindAllByUserId', options)

export const storyControllerFindAllByUserIdOptions = (
  options: Options<StoryControllerFindAllByUserIdData>
) =>
  queryOptions<
    StoryControllerFindAllByUserIdResponse,
    AxiosError<DefaultError>,
    StoryControllerFindAllByUserIdResponse,
    ReturnType<typeof storyControllerFindAllByUserIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await storyControllerFindAllByUserId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: storyControllerFindAllByUserIdQueryKey(options)
  })

export const storyControllerFindAllByUserIdInfiniteQueryKey = (
  options: Options<StoryControllerFindAllByUserIdData>
): QueryKey<Options<StoryControllerFindAllByUserIdData>> =>
  createQueryKey('storyControllerFindAllByUserId', options, true)

export const storyControllerFindAllByUserIdInfiniteOptions = (
  options: Options<StoryControllerFindAllByUserIdData>
) =>
  infiniteQueryOptions<
    StoryControllerFindAllByUserIdResponse,
    AxiosError<DefaultError>,
    InfiniteData<StoryControllerFindAllByUserIdResponse>,
    QueryKey<Options<StoryControllerFindAllByUserIdData>>,
    | number
    | Pick<
        QueryKey<Options<StoryControllerFindAllByUserIdData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<StoryControllerFindAllByUserIdData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam
                }
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await storyControllerFindAllByUserId({
          ...options,
          ...params,
          signal,
          throwOnError: true
        })
        return data
      },
      queryKey: storyControllerFindAllByUserIdInfiniteQueryKey(options)
    }
  )

export const storyControllerRemoveMutation = (
  options?: Partial<Options<StoryControllerRemoveData>>
): UseMutationOptions<
  StoryControllerRemoveResponse,
  AxiosError<DefaultError>,
  Options<StoryControllerRemoveData>
> => {
  const mutationOptions: UseMutationOptions<
    StoryControllerRemoveResponse,
    AxiosError<DefaultError>,
    Options<StoryControllerRemoveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await storyControllerRemove({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const storyControllerFindOneQueryKey = (
  options: Options<StoryControllerFindOneData>
) => createQueryKey('storyControllerFindOne', options)

export const storyControllerFindOneOptions = (
  options: Options<StoryControllerFindOneData>
) =>
  queryOptions<
    StoryControllerFindOneResponse,
    AxiosError<DefaultError>,
    StoryControllerFindOneResponse,
    ReturnType<typeof storyControllerFindOneQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await storyControllerFindOne({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: storyControllerFindOneQueryKey(options)
  })

export const storyControllerUpdateMutation = (
  options?: Partial<Options<StoryControllerUpdateData>>
): UseMutationOptions<
  StoryControllerUpdateResponse,
  AxiosError<DefaultError>,
  Options<StoryControllerUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    StoryControllerUpdateResponse,
    AxiosError<DefaultError>,
    Options<StoryControllerUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await storyControllerUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:send (client -> server)
 *
 * Client emits `message:send`. Server acknowledges with the created message and emits `message:new` (receiver) and `message:sent` (sender).
 */
export const postWsMessagesMessageSendMutation = (
  options?: Partial<Options<PostWsMessagesMessageSendData>>
): UseMutationOptions<
  PostWsMessagesMessageSendResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesMessageSendData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesMessageSendResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesMessageSendData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesMessageSend({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:update (client -> server)
 *
 * Client emits `message:update`. Server acknowledges with the updated message and emits `message:updated` to both participants.
 */
export const postWsMessagesMessageUpdateMutation = (
  options?: Partial<Options<PostWsMessagesMessageUpdateData>>
): UseMutationOptions<
  PostWsMessagesMessageUpdateResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesMessageUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesMessageUpdateResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesMessageUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesMessageUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:delete (client -> server)
 *
 * Client emits `message:delete`. Server emits `message:deleted` to both participants.
 */
export const postWsMessagesMessageDeleteMutation = (
  options?: Partial<Options<PostWsMessagesMessageDeleteData>>
): UseMutationOptions<
  PostWsMessagesMessageDeleteResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesMessageDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesMessageDeleteResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesMessageDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesMessageDelete({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:new (server -> client)
 *
 * Emitted to the receiver when a new message is created.
 */
export const postWsMessagesEventMessageNewMutation = (
  options?: Partial<Options<PostWsMessagesEventMessageNewData>>
): UseMutationOptions<
  PostWsMessagesEventMessageNewResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesEventMessageNewData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesEventMessageNewResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesEventMessageNewData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesEventMessageNew({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:sent (server -> client)
 *
 * Emitted to the sender after `message:send` succeeds.
 */
export const postWsMessagesEventMessageSentMutation = (
  options?: Partial<Options<PostWsMessagesEventMessageSentData>>
): UseMutationOptions<
  PostWsMessagesEventMessageSentResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesEventMessageSentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesEventMessageSentResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesEventMessageSentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesEventMessageSent({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:updated (server -> client)
 *
 * Emitted to both participants after a message update.
 */
export const postWsMessagesEventMessageUpdatedMutation = (
  options?: Partial<Options<PostWsMessagesEventMessageUpdatedData>>
): UseMutationOptions<
  PostWsMessagesEventMessageUpdatedResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesEventMessageUpdatedData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesEventMessageUpdatedResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesEventMessageUpdatedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesEventMessageUpdated({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * message:deleted (server -> client)
 *
 * Emitted to both participants after a message is deleted.
 */
export const postWsMessagesEventMessageDeletedMutation = (
  options?: Partial<Options<PostWsMessagesEventMessageDeletedData>>
): UseMutationOptions<
  PostWsMessagesEventMessageDeletedResponse,
  AxiosError<DefaultError>,
  Options<PostWsMessagesEventMessageDeletedData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsMessagesEventMessageDeletedResponse,
    AxiosError<DefaultError>,
    Options<PostWsMessagesEventMessageDeletedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsMessagesEventMessageDeleted({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * conversation:new (server -> client)
 *
 * Emitted when a new conversation is created.
 */
export const postWsConversationsEventConversationNewMutation = (
  options?: Partial<Options<PostWsConversationsEventConversationNewData>>
): UseMutationOptions<
  PostWsConversationsEventConversationNewResponse,
  AxiosError<DefaultError>,
  Options<PostWsConversationsEventConversationNewData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsConversationsEventConversationNewResponse,
    AxiosError<DefaultError>,
    Options<PostWsConversationsEventConversationNewData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsConversationsEventConversationNew({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * conversation:deleted (server -> client)
 *
 * Emitted when a conversation is deleted.
 */
export const postWsConversationsEventConversationDeletedMutation = (
  options?: Partial<Options<PostWsConversationsEventConversationDeletedData>>
): UseMutationOptions<
  PostWsConversationsEventConversationDeletedResponse,
  AxiosError<DefaultError>,
  Options<PostWsConversationsEventConversationDeletedData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsConversationsEventConversationDeletedResponse,
    AxiosError<DefaultError>,
    Options<PostWsConversationsEventConversationDeletedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsConversationsEventConversationDeleted({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * user:online:list:request (client -> server)
 *
 * Client emits `user:online:list:request`. Server emits `user:online:list` with the current online user ids.
 */
export const postWsUsersUserOnlineListRequestMutation = (
  options?: Partial<Options<PostWsUsersUserOnlineListRequestData>>
): UseMutationOptions<
  PostWsUsersUserOnlineListRequestResponse,
  AxiosError<DefaultError>,
  Options<PostWsUsersUserOnlineListRequestData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsUsersUserOnlineListRequestResponse,
    AxiosError<DefaultError>,
    Options<PostWsUsersUserOnlineListRequestData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsUsersUserOnlineListRequest({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * user:online (server -> client)
 *
 * Emitted when a user comes online.
 */
export const postWsUsersEventUserOnlineMutation = (
  options?: Partial<Options<PostWsUsersEventUserOnlineData>>
): UseMutationOptions<
  PostWsUsersEventUserOnlineResponse,
  AxiosError<DefaultError>,
  Options<PostWsUsersEventUserOnlineData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsUsersEventUserOnlineResponse,
    AxiosError<DefaultError>,
    Options<PostWsUsersEventUserOnlineData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsUsersEventUserOnline({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * user:offline (server -> client)
 *
 * Emitted when a user goes offline.
 */
export const postWsUsersEventUserOfflineMutation = (
  options?: Partial<Options<PostWsUsersEventUserOfflineData>>
): UseMutationOptions<
  PostWsUsersEventUserOfflineResponse,
  AxiosError<DefaultError>,
  Options<PostWsUsersEventUserOfflineData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsUsersEventUserOfflineResponse,
    AxiosError<DefaultError>,
    Options<PostWsUsersEventUserOfflineData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsUsersEventUserOffline({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

/**
 * user:online:list (server -> client)
 *
 * Emitted with the list of currently online user ids.
 */
export const postWsUsersEventUserOnlineListMutation = (
  options?: Partial<Options<PostWsUsersEventUserOnlineListData>>
): UseMutationOptions<
  PostWsUsersEventUserOnlineListResponse,
  AxiosError<DefaultError>,
  Options<PostWsUsersEventUserOnlineListData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWsUsersEventUserOnlineListResponse,
    AxiosError<DefaultError>,
    Options<PostWsUsersEventUserOnlineListData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWsUsersEventUserOnlineList({
        ...options,
        ...fnOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}
