// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape
} from './client'
import { client } from './client.gen'
import type {
  AuthControllerLoginData,
  AuthControllerLoginResponses,
  AuthControllerLogoutData,
  AuthControllerLogoutResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshResponses,
  AuthControllerRegisterData,
  AuthControllerRegisterResponses,
  ConversationControllerCreateData,
  ConversationControllerCreateResponses,
  ConversationControllerFindAllConversationMessagesData,
  ConversationControllerFindAllConversationMessagesResponses,
  ConversationControllerFindAllData,
  ConversationControllerFindAllResponses,
  ConversationControllerFindAllSuggestionsData,
  ConversationControllerFindAllSuggestionsResponses,
  ConversationControllerFindOneByUserIdData,
  ConversationControllerFindOneByUserIdResponses,
  ConversationControllerFindOneData,
  ConversationControllerFindOneResponses,
  ConversationControllerRemoveData,
  ConversationControllerRemoveResponses,
  MessageControllerCreateData,
  MessageControllerCreateResponses,
  MessageControllerFindOneData,
  MessageControllerFindOneResponses,
  MessageControllerRemoveData,
  MessageControllerRemoveResponses,
  MessageControllerUpdateData,
  MessageControllerUpdateResponses,
  PostCommentsControllerCreateCommentData,
  PostCommentsControllerCreateCommentResponses,
  PostCommentsControllerFindAllCommentsData,
  PostCommentsControllerFindAllCommentsResponses,
  PostCommentsControllerRemoveCommentData,
  PostCommentsControllerRemoveCommentResponses,
  PostCommentsControllerUpdateCommentData,
  PostCommentsControllerUpdateCommentResponses,
  PostLikesControllerCreateLikeData,
  PostLikesControllerCreateLikeResponses,
  PostLikesControllerFindAllLikesData,
  PostLikesControllerFindAllLikesResponses,
  PostLikesControllerRemoveLikeData,
  PostLikesControllerRemoveLikeResponses,
  PostsControllerCreateData,
  PostsControllerCreateResponses,
  PostsControllerFindAllData,
  PostsControllerFindAllMyData,
  PostsControllerFindAllMyResponses,
  PostsControllerFindAllResponses,
  PostsControllerFindOneData,
  PostsControllerFindOneResponses,
  PostsControllerRemoveData,
  PostsControllerRemoveResponses,
  PostsControllerUpdateData,
  PostsControllerUpdateResponses,
  PostWsConversationsEventConversationDeletedData,
  PostWsConversationsEventConversationDeletedResponses,
  PostWsConversationsEventConversationNewData,
  PostWsConversationsEventConversationNewResponses,
  PostWsMessagesEventMessageDeletedData,
  PostWsMessagesEventMessageDeletedResponses,
  PostWsMessagesEventMessageNewData,
  PostWsMessagesEventMessageNewResponses,
  PostWsMessagesEventMessageSentData,
  PostWsMessagesEventMessageSentResponses,
  PostWsMessagesEventMessageUpdatedData,
  PostWsMessagesEventMessageUpdatedResponses,
  PostWsMessagesMessageDeleteData,
  PostWsMessagesMessageDeleteResponses,
  PostWsMessagesMessageSendData,
  PostWsMessagesMessageSendResponses,
  PostWsMessagesMessageUpdateData,
  PostWsMessagesMessageUpdateResponses,
  PostWsUsersEventUserOfflineData,
  PostWsUsersEventUserOfflineResponses,
  PostWsUsersEventUserOnlineData,
  PostWsUsersEventUserOnlineListData,
  PostWsUsersEventUserOnlineListResponses,
  PostWsUsersEventUserOnlineResponses,
  PostWsUsersUserOnlineListRequestData,
  PostWsUsersUserOnlineListRequestResponses,
  ProfileControllerMeData,
  ProfileControllerMeDetailedData,
  ProfileControllerMeDetailedResponses,
  ProfileControllerMeResponses,
  ProfileControllerUpdateData,
  ProfileControllerUpdateResponses,
  SubscriptionControllerFindAllFollowersData,
  SubscriptionControllerFindAllFollowersResponses,
  SubscriptionControllerFindAllFollowingData,
  SubscriptionControllerFindAllFollowingResponses,
  SubscriptionControllerFindOneCountData,
  SubscriptionControllerFindOneCountResponses,
  SubscriptionControllerFollowData,
  SubscriptionControllerFollowResponses,
  SubscriptionControllerRemoveFollowerData,
  SubscriptionControllerRemoveFollowerResponses,
  SubscriptionControllerUnfollowData,
  SubscriptionControllerUnfollowResponses,
  UploadControllerDeleteData,
  UploadControllerDeleteResponses,
  UploadControllerUploadData,
  UploadControllerUploadResponses,
  UserControllerChangePasswordData,
  UserControllerChangePasswordResponses,
  UserControllerFindAllData,
  UserControllerFindAllResponses,
  UserControllerFindOneData,
  UserControllerFindOneResponses,
  UserControllerRemoveData,
  UserControllerRemoveResponses,
  UserControllerUpdateData,
  UserControllerUpdateResponses
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Validation pattern for password:
 * `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>/?]).{8,}$/`
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AuthControllerLoginResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const authControllerLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerLogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthControllerLogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/logout',
    ...options
  })

export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerRefreshData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    AuthControllerRefreshResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/refresh',
    ...options
  })

export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    UserControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users',
    ...options
  })

export const userControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UserControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options
  })

export const userControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options
  })

export const userControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UserControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const userControllerChangePassword = <
  ThrowOnError extends boolean = false
>(
  options: Options<UserControllerChangePasswordData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UserControllerChangePasswordResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const profileControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<ProfileControllerMeData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProfileControllerMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/profile/me',
    ...options
  })

export const profileControllerMeDetailed = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ProfileControllerMeDetailedData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ProfileControllerMeDetailedResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/profile/me/detailed',
    ...options
  })

export const profileControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProfileControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    ProfileControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const postsControllerFindAll = <ThrowOnError extends boolean = false>(
  options?: Options<PostsControllerFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    PostsControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts',
    ...options
  })

export const postsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostsControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const postsControllerFindAllMy = <ThrowOnError extends boolean = false>(
  options?: Options<PostsControllerFindAllMyData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    PostsControllerFindAllMyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/my',
    ...options
  })

export const postsControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    PostsControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}',
    ...options
  })

export const postsControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    PostsControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}',
    ...options
  })

export const postsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PostsControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PostsControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const postCommentsControllerFindAllComments = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostCommentsControllerFindAllCommentsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    PostCommentsControllerFindAllCommentsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/comments',
    ...options
  })

export const postCommentsControllerCreateComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostCommentsControllerCreateCommentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostCommentsControllerCreateCommentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/comments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const postCommentsControllerRemoveComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostCommentsControllerRemoveCommentData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    PostCommentsControllerRemoveCommentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/comments/{commentId}',
    ...options
  })

export const postCommentsControllerUpdateComment = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostCommentsControllerUpdateCommentData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PostCommentsControllerUpdateCommentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/comments/{commentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const postLikesControllerRemoveLike = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostLikesControllerRemoveLikeData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    PostLikesControllerRemoveLikeResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/likes',
    ...options
  })

export const postLikesControllerFindAllLikes = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostLikesControllerFindAllLikesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    PostLikesControllerFindAllLikesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/likes',
    ...options
  })

export const postLikesControllerCreateLike = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostLikesControllerCreateLikeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostLikesControllerCreateLikeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/posts/{id}/likes',
    ...options
  })

export const uploadControllerUpload = <ThrowOnError extends boolean = false>(
  options: Options<UploadControllerUploadData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadControllerUploadResponses,
    unknown,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers
    }
  })

export const uploadControllerDelete = <ThrowOnError extends boolean = false>(
  options: Options<UploadControllerDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UploadControllerDeleteResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/upload/{id}',
    ...options
  })

export const messageControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    MessageControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/messages/{id}',
    ...options
  })

export const messageControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    MessageControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/messages/{id}',
    ...options
  })

export const messageControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    MessageControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/messages/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const messageControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<MessageControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    MessageControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const subscriptionControllerFindAllFollowers = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindAllFollowersData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SubscriptionControllerFindAllFollowersResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/followers/{id}',
    ...options
  })

export const subscriptionControllerFindAllFollowing = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindAllFollowingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SubscriptionControllerFindAllFollowingResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/following/{id}',
    ...options
  })

export const subscriptionControllerFindOneCount = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFindOneCountData, ThrowOnError>
) =>
  (options.client ?? client).get<
    SubscriptionControllerFindOneCountResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/count/{id}',
    ...options
  })

export const subscriptionControllerFollow = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerFollowData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubscriptionControllerFollowResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/follow/{id}',
    ...options
  })

export const subscriptionControllerUnfollow = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerUnfollowData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubscriptionControllerUnfollowResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/unfollow/{id}',
    ...options
  })

export const subscriptionControllerRemoveFollower = <
  ThrowOnError extends boolean = false
>(
  options: Options<SubscriptionControllerRemoveFollowerData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SubscriptionControllerRemoveFollowerResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/subscription/unfollow/follower/{id}',
    ...options
  })

export const conversationControllerFindAll = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ConversationControllerFindAllData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ConversationControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations',
    ...options
  })

export const conversationControllerCreate = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ConversationControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

export const conversationControllerFindAllSuggestions = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ConversationControllerFindAllSuggestionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ConversationControllerFindAllSuggestionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations/suggestions',
    ...options
  })

export const conversationControllerFindOneByUserId = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerFindOneByUserIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ConversationControllerFindOneByUserIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations/user/{userId}',
    ...options
  })

export const conversationControllerFindAllConversationMessages = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    ConversationControllerFindAllConversationMessagesData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ConversationControllerFindAllConversationMessagesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations/{id}/messages',
    ...options
  })

export const conversationControllerRemove = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerRemoveData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ConversationControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations/{id}',
    ...options
  })

export const conversationControllerFindOne = <
  ThrowOnError extends boolean = false
>(
  options: Options<ConversationControllerFindOneData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ConversationControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/conversations/{id}',
    ...options
  })

/**
 * message:send (client -> server)
 *
 * Client emits `message:send`. Server acknowledges with the created message and emits `message:new` (receiver) and `message:sent` (sender).
 */
export const postWsMessagesMessageSend = <ThrowOnError extends boolean = false>(
  options: Options<PostWsMessagesMessageSendData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostWsMessagesMessageSendResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/message-send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * message:update (client -> server)
 *
 * Client emits `message:update`. Server acknowledges with the updated message and emits `message:updated` to both participants.
 */
export const postWsMessagesMessageUpdate = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostWsMessagesMessageUpdateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostWsMessagesMessageUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/message-update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * message:delete (client -> server)
 *
 * Client emits `message:delete`. Server emits `message:deleted` to both participants.
 */
export const postWsMessagesMessageDelete = <
  ThrowOnError extends boolean = false
>(
  options: Options<PostWsMessagesMessageDeleteData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostWsMessagesMessageDeleteResponses,
    unknown,
    ThrowOnError
  >({
    url: '/ws/messages/message-delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * message:new (server -> client)
 *
 * Emitted to the receiver when a new message is created.
 */
export const postWsMessagesEventMessageNew = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsMessagesEventMessageNewData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsMessagesEventMessageNewResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/event-message-new',
    ...options
  })

/**
 * message:sent (server -> client)
 *
 * Emitted to the sender after `message:send` succeeds.
 */
export const postWsMessagesEventMessageSent = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsMessagesEventMessageSentData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsMessagesEventMessageSentResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/event-message-sent',
    ...options
  })

/**
 * message:updated (server -> client)
 *
 * Emitted to both participants after a message update.
 */
export const postWsMessagesEventMessageUpdated = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsMessagesEventMessageUpdatedData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsMessagesEventMessageUpdatedResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/event-message-updated',
    ...options
  })

/**
 * message:deleted (server -> client)
 *
 * Emitted to both participants after a message is deleted.
 */
export const postWsMessagesEventMessageDeleted = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsMessagesEventMessageDeletedData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsMessagesEventMessageDeletedResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/messages/event-message-deleted',
    ...options
  })

/**
 * conversation:new (server -> client)
 *
 * Emitted when a new conversation is created.
 */
export const postWsConversationsEventConversationNew = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsConversationsEventConversationNewData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsConversationsEventConversationNewResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/conversations/event-conversation-new',
    ...options
  })

/**
 * conversation:deleted (server -> client)
 *
 * Emitted when a conversation is deleted.
 */
export const postWsConversationsEventConversationDeleted = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    PostWsConversationsEventConversationDeletedData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).post<
    PostWsConversationsEventConversationDeletedResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/conversations/event-conversation-deleted',
    ...options
  })

/**
 * user:online:list:request (client -> server)
 *
 * Client emits `user:online:list:request`. Server emits `user:online:list` with the current online user ids.
 */
export const postWsUsersUserOnlineListRequest = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsUsersUserOnlineListRequestData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsUsersUserOnlineListRequestResponses,
    unknown,
    ThrowOnError
  >({ url: '/ws/users/user-online-list-request', ...options })

/**
 * user:online (server -> client)
 *
 * Emitted when a user comes online.
 */
export const postWsUsersEventUserOnline = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsUsersEventUserOnlineData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsUsersEventUserOnlineResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/users/event-user-online',
    ...options
  })

/**
 * user:offline (server -> client)
 *
 * Emitted when a user goes offline.
 */
export const postWsUsersEventUserOffline = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsUsersEventUserOfflineData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsUsersEventUserOfflineResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/users/event-user-offline',
    ...options
  })

/**
 * user:online:list (server -> client)
 *
 * Emitted with the list of currently online user ids.
 */
export const postWsUsersEventUserOnlineList = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PostWsUsersEventUserOnlineListData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostWsUsersEventUserOnlineListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/ws/users/event-user-online-list',
    ...options
  })
