// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string
}

export type ResponseFileDto = {
  readonly id: number
  url: string
  type?: string | null
  readonly uploadedAt: string
}

export type ResponseProfileDto = {
  readonly id: number
  fullName: string
  avatar?: ResponseFileDto | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
  readonly createdAt: string
}

export type ResponseUserDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  readonly followersCount: number
  readonly followingCount: number
  readonly isFollowing: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
  readonly lastActivityAt: string
}

export type ResponseRegisterDto = {
  user: ResponseUserDto
  accessToken: string
}

export type BaseResponseDto = {
  success: boolean
  message?: string | null
  data?: {
    [key: string]: unknown
  } | null
}

export type CreateUserDto = {
  email: string
  username: string
  fullName: string
  password: string
}

export type ResponseLoginDto = {
  user: ResponseUserDto
  accessToken: string
}

export type CreateLoginDto = {
  email: string
  password: string
}

export type EmptyResponseDto = {
  [key: string]: unknown
}

export type ResponseRefreshDto = {
  readonly accessToken: string
}

export type PaginatedResponseDto = {
  success: boolean
  message?: string | null
  data?: {
    [key: string]: unknown
  } | null
  total: number
  page: number
  pageSize: number
  totalPages: number
  nextPage?: number | null
  prevPage?: number | null
}

export type UpdateUserDto = {
  email?: string
  username?: string
}

export type CreateChangePasswordDto = {
  oldPassword: string
  newPassword: string
}

export type ResponseProfileDetailedDto = {
  user: ResponseUserDto
}

export type UpdateProfileDto = {
  phone?: string | null
  biography?: string | null
  fullName?: string
  avatar?: number | null
  birthDay?: string | null
}

export type ResponseUserProfileDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
  readonly lastActivityAt: string
}

export type ResponsePostFileDto = {
  file: ResponseFileDto
}

export type ResponsePostDto = {
  readonly id: number
  content: string
  isLiked: boolean
  user: ResponseUserProfileDto
  files?: Array<ResponsePostFileDto> | null
  likesCount: number
  commentsCount: number
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreatePostDto = {
  content: string
  files: Array<number>
}

export type UpdatePostDto = {
  content?: string
  files?: Array<number>
}

export type ResponsePostCommentDto = {
  readonly id: number
  user: ResponseUserProfileDto
  content: string
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreatePostCommentDto = {
  content: string
}

export type ResponseUserProfileIsFollowingDto = {
  readonly id: number
  username: string
  email: string
  readonly activationLink?: string | null
  readonly isActivated: boolean
  profile: ResponseProfileDto
  readonly createdAt: string
  readonly lastActivityAt: string
  readonly isFollowing: boolean
}

export type ResponsePostLikeDto = {
  readonly id: number
  user: ResponseUserProfileIsFollowingDto
  readonly createdAt: string
}

export type ResponseUploadDto = {
  readonly id: number
  secure_url: string
  type: string
}

export type CreateUploadDto = {
  file: Blob | File
  folder?: string | null
}

export type ResponseMessageDto = {
  readonly id: number
  readonly senderId: number
  receiverId: number
  conversationId: number
  content?: string | null
  readonly isEdited: boolean
  files?: Array<ResponseFileDto> | null
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreateMessageDto = {
  receiverId: number
  conversationId: number
  content?: string | null
  fileIds?: Array<number> | null
}

export type UpdateMessageDto = {
  content?: string | null
  fileIds?: Array<number> | null
  id: number
}

export type ResponseSubscriptionDto = {
  readonly id: number
  user: ResponseUserProfileDto
  readonly createdAt: string
}

export type ResponseSubscriptionCountDto = {
  followers: number
  following: number
}

export type ResponseConversationDto = {
  readonly id: number
  receiver: ResponseUserProfileDto
  readonly createdAt: string
  readonly updatedAt: string
}

export type CreateConversationDto = {
  receiverId: number
}

export type ResponseStoryDto = {
  readonly id: number
  previewUrl?: string | null
  isViewed: boolean
  user: ResponseUserProfileDto
  files?: Array<ResponseFileDto> | null
  readonly createdAt: string
  readonly updatedAt: string
}

export type ResponseStoryViewerDto = {
  readonly id: number
  user: ResponseUserProfileDto
  readonly createdAt: string
}

export type CreateStoryDto = {
  previewUrl?: string | null
  files: Array<number>
}

export type UpdateStoryDto = {
  previewUrl?: string | null
  files?: Array<number>
}

export type DeleteMessageDto = {
  id: number
}

export type ResponseFileDtoWritable = {
  url: string
  type?: string | null
}

export type ResponseProfileDtoWritable = {
  fullName: string
  avatar?: ResponseFileDtoWritable | null
  birthDay?: string | null
  phone?: string | null
  biography?: string | null
}

export type ResponseUserDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type ResponseRegisterDtoWritable = {
  user: ResponseUserDtoWritable
  accessToken: string
}

export type ResponseLoginDtoWritable = {
  user: ResponseUserDtoWritable
  accessToken: string
}

export type EmptyResponseDtoWritable = {
  [key: string]: unknown
}

export type ResponseProfileDetailedDtoWritable = {
  user: ResponseUserDtoWritable
}

export type ResponseUserProfileDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type ResponsePostFileDtoWritable = {
  file: ResponseFileDtoWritable
}

export type ResponsePostDtoWritable = {
  content: string
  isLiked: boolean
  user: ResponseUserProfileDtoWritable
  files?: Array<ResponsePostFileDtoWritable> | null
  likesCount: number
  commentsCount: number
}

export type ResponsePostCommentDtoWritable = {
  user: ResponseUserProfileDtoWritable
  content: string
}

export type ResponseUserProfileIsFollowingDtoWritable = {
  username: string
  email: string
  profile: ResponseProfileDtoWritable
}

export type ResponsePostLikeDtoWritable = {
  user: ResponseUserProfileIsFollowingDtoWritable
}

export type ResponseUploadDtoWritable = {
  secure_url: string
  type: string
}

export type ResponseMessageDtoWritable = {
  receiverId: number
  conversationId: number
  content?: string | null
  files?: Array<ResponseFileDtoWritable> | null
}

export type ResponseSubscriptionDtoWritable = {
  user: ResponseUserProfileDtoWritable
}

export type ResponseConversationDtoWritable = {
  receiver: ResponseUserProfileDtoWritable
}

export type ResponseStoryDtoWritable = {
  previewUrl?: string | null
  isViewed: boolean
  user: ResponseUserProfileDtoWritable
  files?: Array<ResponseFileDtoWritable> | null
}

export type ResponseStoryViewerDtoWritable = {
  user: ResponseUserProfileDtoWritable
}

export type AuthControllerRegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/api/auth/register'
}

export type AuthControllerRegisterResponses = {
  200: BaseResponseDto & {
    data?: ResponseRegisterDto
  }
}

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses]

export type AuthControllerLoginData = {
  body: CreateLoginDto
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type AuthControllerLoginResponses = {
  200: BaseResponseDto & {
    data?: ResponseLoginDto
  }
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/logout'
}

export type AuthControllerLogoutResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type AuthControllerLogoutResponse =
  AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses]

export type AuthControllerRefreshData = {
  body?: never
  path?: never
  query?: never
  url: '/api/auth/refresh'
}

export type AuthControllerRefreshResponses = {
  200: BaseResponseDto & {
    data?: ResponseRefreshDto
  }
}

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses]

export type UserControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/users'
}

export type UserControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseUserDto>
  }
}

export type UserControllerFindAllResponse =
  UserControllerFindAllResponses[keyof UserControllerFindAllResponses]

export type UserControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerRemoveResponses = {
  204: void
}

export type UserControllerRemoveResponse =
  UserControllerRemoveResponses[keyof UserControllerRemoveResponses]

export type UserControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerFindOneResponse =
  UserControllerFindOneResponses[keyof UserControllerFindOneResponses]

export type UserControllerUpdateData = {
  body: UpdateUserDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}'
}

export type UserControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseUserDto
  }
}

export type UserControllerUpdateResponse =
  UserControllerUpdateResponses[keyof UserControllerUpdateResponses]

export type UserControllerChangePasswordData = {
  body: CreateChangePasswordDto
  path: {
    id: string
  }
  query?: never
  url: '/api/users/{id}/change-password'
}

export type UserControllerChangePasswordResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type UserControllerChangePasswordResponse =
  UserControllerChangePasswordResponses[keyof UserControllerChangePasswordResponses]

export type ProfileControllerMeData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me'
}

export type ProfileControllerMeResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerMeResponse =
  ProfileControllerMeResponses[keyof ProfileControllerMeResponses]

export type ProfileControllerMeDetailedData = {
  body?: never
  path?: never
  query?: never
  url: '/api/profile/me/detailed'
}

export type ProfileControllerMeDetailedResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDetailedDto
  }
}

export type ProfileControllerMeDetailedResponse =
  ProfileControllerMeDetailedResponses[keyof ProfileControllerMeDetailedResponses]

export type ProfileControllerUpdateData = {
  body: UpdateProfileDto
  path?: never
  query?: never
  url: '/api/profile'
}

export type ProfileControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseProfileDto
  }
}

export type ProfileControllerUpdateResponse =
  ProfileControllerUpdateResponses[keyof ProfileControllerUpdateResponses]

export type PostsControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts'
}

export type PostsControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostDto>
  }
}

export type PostsControllerFindAllResponse =
  PostsControllerFindAllResponses[keyof PostsControllerFindAllResponses]

export type PostsControllerCreateData = {
  body: CreatePostDto
  path?: never
  query?: never
  url: '/api/posts'
}

export type PostsControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostsControllerCreateResponse =
  PostsControllerCreateResponses[keyof PostsControllerCreateResponses]

export type PostsControllerFindAllMyData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts/my'
}

export type PostsControllerFindAllMyResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostDto>
  }
}

export type PostsControllerFindAllMyResponse =
  PostsControllerFindAllMyResponses[keyof PostsControllerFindAllMyResponses]

export type PostsControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostsControllerRemoveResponses = {
  204: void
}

export type PostsControllerRemoveResponse =
  PostsControllerRemoveResponses[keyof PostsControllerRemoveResponses]

export type PostsControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostsControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostsControllerFindOneResponse =
  PostsControllerFindOneResponses[keyof PostsControllerFindOneResponses]

export type PostsControllerUpdateData = {
  body: UpdatePostDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}'
}

export type PostsControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponsePostDto
  }
}

export type PostsControllerUpdateResponse =
  PostsControllerUpdateResponses[keyof PostsControllerUpdateResponses]

export type PostCommentsControllerFindAllCommentsData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts/{id}/comments'
}

export type PostCommentsControllerFindAllCommentsResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostCommentDto>
  }
}

export type PostCommentsControllerFindAllCommentsResponse =
  PostCommentsControllerFindAllCommentsResponses[keyof PostCommentsControllerFindAllCommentsResponses]

export type PostCommentsControllerCreateCommentData = {
  body: CreatePostCommentDto
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/comments'
}

export type PostCommentsControllerCreateCommentResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostCommentsControllerCreateCommentResponse =
  PostCommentsControllerCreateCommentResponses[keyof PostCommentsControllerCreateCommentResponses]

export type PostCommentsControllerRemoveCommentData = {
  body?: never
  path: {
    id: string
    commentId: string
  }
  query?: never
  url: '/api/posts/{id}/comments/{commentId}'
}

export type PostCommentsControllerRemoveCommentResponses = {
  204: void
}

export type PostCommentsControllerRemoveCommentResponse =
  PostCommentsControllerRemoveCommentResponses[keyof PostCommentsControllerRemoveCommentResponses]

export type PostCommentsControllerUpdateCommentData = {
  body: CreatePostCommentDto
  path: {
    id: string
    commentId: string
  }
  query?: never
  url: '/api/posts/{id}/comments/{commentId}'
}

export type PostCommentsControllerUpdateCommentResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostCommentsControllerUpdateCommentResponse =
  PostCommentsControllerUpdateCommentResponses[keyof PostCommentsControllerUpdateCommentResponses]

export type PostLikesControllerRemoveLikeData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/likes'
}

export type PostLikesControllerRemoveLikeResponses = {
  204: void
}

export type PostLikesControllerRemoveLikeResponse =
  PostLikesControllerRemoveLikeResponses[keyof PostLikesControllerRemoveLikeResponses]

export type PostLikesControllerFindAllLikesData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/posts/{id}/likes'
}

export type PostLikesControllerFindAllLikesResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponsePostLikeDto>
  }
}

export type PostLikesControllerFindAllLikesResponse =
  PostLikesControllerFindAllLikesResponses[keyof PostLikesControllerFindAllLikesResponses]

export type PostLikesControllerCreateLikeData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/posts/{id}/likes'
}

export type PostLikesControllerCreateLikeResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type PostLikesControllerCreateLikeResponse =
  PostLikesControllerCreateLikeResponses[keyof PostLikesControllerCreateLikeResponses]

export type UploadControllerUploadData = {
  body: CreateUploadDto
  path?: never
  query?: never
  url: '/api/upload'
}

export type UploadControllerUploadResponses = {
  200: BaseResponseDto & {
    data?: ResponseUploadDto
  }
}

export type UploadControllerUploadResponse =
  UploadControllerUploadResponses[keyof UploadControllerUploadResponses]

export type UploadControllerDeleteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/upload/{id}'
}

export type UploadControllerDeleteResponses = {
  204: void
}

export type UploadControllerDeleteResponse =
  UploadControllerDeleteResponses[keyof UploadControllerDeleteResponses]

export type MessageControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/messages/{id}'
}

export type MessageControllerRemoveResponses = {
  204: void
}

export type MessageControllerRemoveResponse =
  MessageControllerRemoveResponses[keyof MessageControllerRemoveResponses]

export type MessageControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/messages/{id}'
}

export type MessageControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerFindOneResponse =
  MessageControllerFindOneResponses[keyof MessageControllerFindOneResponses]

export type MessageControllerUpdateData = {
  body: UpdateMessageDto
  path: {
    id: string
  }
  query?: never
  url: '/api/messages/{id}'
}

export type MessageControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerUpdateResponse =
  MessageControllerUpdateResponses[keyof MessageControllerUpdateResponses]

export type MessageControllerCreateData = {
  body: CreateMessageDto
  path?: never
  query?: never
  url: '/api/messages'
}

export type MessageControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponseMessageDto
  }
}

export type MessageControllerCreateResponse =
  MessageControllerCreateResponses[keyof MessageControllerCreateResponses]

export type SubscriptionControllerFindAllFollowersData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/subscription/followers/{id}'
}

export type SubscriptionControllerFindAllFollowersResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseSubscriptionDto>
  }
}

export type SubscriptionControllerFindAllFollowersResponse =
  SubscriptionControllerFindAllFollowersResponses[keyof SubscriptionControllerFindAllFollowersResponses]

export type SubscriptionControllerFindAllFollowingData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/subscription/following/{id}'
}

export type SubscriptionControllerFindAllFollowingResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseSubscriptionDto>
  }
}

export type SubscriptionControllerFindAllFollowingResponse =
  SubscriptionControllerFindAllFollowingResponses[keyof SubscriptionControllerFindAllFollowingResponses]

export type SubscriptionControllerFindOneCountData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/count/{id}'
}

export type SubscriptionControllerFindOneCountResponses = {
  200: BaseResponseDto & {
    data?: ResponseSubscriptionCountDto
  }
}

export type SubscriptionControllerFindOneCountResponse =
  SubscriptionControllerFindOneCountResponses[keyof SubscriptionControllerFindOneCountResponses]

export type SubscriptionControllerFollowData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/follow/{id}'
}

export type SubscriptionControllerFollowResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type SubscriptionControllerFollowResponse =
  SubscriptionControllerFollowResponses[keyof SubscriptionControllerFollowResponses]

export type SubscriptionControllerUnfollowData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/unfollow/{id}'
}

export type SubscriptionControllerUnfollowResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type SubscriptionControllerUnfollowResponse =
  SubscriptionControllerUnfollowResponses[keyof SubscriptionControllerUnfollowResponses]

export type SubscriptionControllerRemoveFollowerData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/subscription/unfollow/follower/{id}'
}

export type SubscriptionControllerRemoveFollowerResponses = {
  200: BaseResponseDto & {
    data?: EmptyResponseDto
  }
}

export type SubscriptionControllerRemoveFollowerResponse =
  SubscriptionControllerRemoveFollowerResponses[keyof SubscriptionControllerRemoveFollowerResponses]

export type ConversationControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/conversations'
}

export type ConversationControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseConversationDto>
  }
}

export type ConversationControllerFindAllResponse =
  ConversationControllerFindAllResponses[keyof ConversationControllerFindAllResponses]

export type ConversationControllerCreateData = {
  body: CreateConversationDto
  path?: never
  query?: never
  url: '/api/conversations'
}

export type ConversationControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponseConversationDto
  }
}

export type ConversationControllerCreateResponse =
  ConversationControllerCreateResponses[keyof ConversationControllerCreateResponses]

export type ConversationControllerFindAllSuggestionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/conversations/suggestions'
}

export type ConversationControllerFindAllSuggestionsResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseUserProfileDto>
  }
}

export type ConversationControllerFindAllSuggestionsResponse =
  ConversationControllerFindAllSuggestionsResponses[keyof ConversationControllerFindAllSuggestionsResponses]

export type ConversationControllerFindOneByUserIdData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: '/api/conversations/user/{userId}'
}

export type ConversationControllerFindOneByUserIdResponses = {
  200: BaseResponseDto & {
    data?: ResponseConversationDto
  }
}

export type ConversationControllerFindOneByUserIdResponse =
  ConversationControllerFindOneByUserIdResponses[keyof ConversationControllerFindOneByUserIdResponses]

export type ConversationControllerFindAllConversationMessagesData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/conversations/{id}/messages'
}

export type ConversationControllerFindAllConversationMessagesResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseMessageDto>
  }
}

export type ConversationControllerFindAllConversationMessagesResponse =
  ConversationControllerFindAllConversationMessagesResponses[keyof ConversationControllerFindAllConversationMessagesResponses]

export type ConversationControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/conversations/{id}'
}

export type ConversationControllerRemoveResponses = {
  204: void
}

export type ConversationControllerRemoveResponse =
  ConversationControllerRemoveResponses[keyof ConversationControllerRemoveResponses]

export type ConversationControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/conversations/{id}'
}

export type ConversationControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseConversationDto
  }
}

export type ConversationControllerFindOneResponse =
  ConversationControllerFindOneResponses[keyof ConversationControllerFindOneResponses]

export type StoryControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/stories'
}

export type StoryControllerFindAllResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseStoryDto>
  }
}

export type StoryControllerFindAllResponse =
  StoryControllerFindAllResponses[keyof StoryControllerFindAllResponses]

export type StoryControllerCreateData = {
  body: CreateStoryDto
  path?: never
  query?: never
  url: '/api/stories'
}

export type StoryControllerCreateResponses = {
  200: BaseResponseDto & {
    data?: ResponseStoryDto
  }
}

export type StoryControllerCreateResponse =
  StoryControllerCreateResponses[keyof StoryControllerCreateResponses]

export type StoryControllerFindAllViewersData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/stories/{id}/viewers'
}

export type StoryControllerFindAllViewersResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseStoryViewerDto>
  }
}

export type StoryControllerFindAllViewersResponse =
  StoryControllerFindAllViewersResponses[keyof StoryControllerFindAllViewersResponses]

export type StoryControllerFindAllByUserIdData = {
  body?: never
  path: {
    userId: string
  }
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number
    /**
     * Number of results to return per page. Maximum: 100
     */
    pageSize?: number
    /**
     * Which field to use when ordering the results.
     */
    ordering?: string
    /**
     * A search term.
     */
    search?: string
  }
  url: '/api/stories/user/{userId}'
}

export type StoryControllerFindAllByUserIdResponses = {
  200: PaginatedResponseDto & {
    data?: Array<ResponseStoryDto>
  }
}

export type StoryControllerFindAllByUserIdResponse =
  StoryControllerFindAllByUserIdResponses[keyof StoryControllerFindAllByUserIdResponses]

export type StoryControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/stories/{id}'
}

export type StoryControllerRemoveResponses = {
  204: void
}

export type StoryControllerRemoveResponse =
  StoryControllerRemoveResponses[keyof StoryControllerRemoveResponses]

export type StoryControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/stories/{id}'
}

export type StoryControllerFindOneResponses = {
  200: BaseResponseDto & {
    data?: ResponseStoryDto
  }
}

export type StoryControllerFindOneResponse =
  StoryControllerFindOneResponses[keyof StoryControllerFindOneResponses]

export type StoryControllerUpdateData = {
  body: UpdateStoryDto
  path: {
    id: string
  }
  query?: never
  url: '/api/stories/{id}'
}

export type StoryControllerUpdateResponses = {
  200: BaseResponseDto & {
    data?: ResponseStoryDto
  }
}

export type StoryControllerUpdateResponse =
  StoryControllerUpdateResponses[keyof StoryControllerUpdateResponses]

export type PostWsMessagesMessageSendData = {
  body: CreateMessageDto
  path?: never
  query?: never
  url: '/ws/messages/message-send'
}

export type PostWsMessagesMessageSendResponses = {
  /**
   * Ack payload.
   */
  200: ResponseMessageDto
}

export type PostWsMessagesMessageSendResponse =
  PostWsMessagesMessageSendResponses[keyof PostWsMessagesMessageSendResponses]

export type PostWsMessagesMessageUpdateData = {
  body: UpdateMessageDto
  path?: never
  query?: never
  url: '/ws/messages/message-update'
}

export type PostWsMessagesMessageUpdateResponses = {
  /**
   * Ack payload.
   */
  200: ResponseMessageDto
}

export type PostWsMessagesMessageUpdateResponse =
  PostWsMessagesMessageUpdateResponses[keyof PostWsMessagesMessageUpdateResponses]

export type PostWsMessagesMessageDeleteData = {
  body: DeleteMessageDto
  path?: never
  query?: never
  url: '/ws/messages/message-delete'
}

export type PostWsMessagesMessageDeleteResponses = {
  /**
   * No ack payload.
   */
  204: void
}

export type PostWsMessagesMessageDeleteResponse =
  PostWsMessagesMessageDeleteResponses[keyof PostWsMessagesMessageDeleteResponses]

export type PostWsMessagesEventMessageNewData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/messages/event-message-new'
}

export type PostWsMessagesEventMessageNewResponses = {
  /**
   * Event payload.
   */
  200: ResponseMessageDto
}

export type PostWsMessagesEventMessageNewResponse =
  PostWsMessagesEventMessageNewResponses[keyof PostWsMessagesEventMessageNewResponses]

export type PostWsMessagesEventMessageSentData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/messages/event-message-sent'
}

export type PostWsMessagesEventMessageSentResponses = {
  /**
   * Event payload.
   */
  200: ResponseMessageDto
}

export type PostWsMessagesEventMessageSentResponse =
  PostWsMessagesEventMessageSentResponses[keyof PostWsMessagesEventMessageSentResponses]

export type PostWsMessagesEventMessageUpdatedData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/messages/event-message-updated'
}

export type PostWsMessagesEventMessageUpdatedResponses = {
  /**
   * Event payload.
   */
  200: ResponseMessageDto
}

export type PostWsMessagesEventMessageUpdatedResponse =
  PostWsMessagesEventMessageUpdatedResponses[keyof PostWsMessagesEventMessageUpdatedResponses]

export type PostWsMessagesEventMessageDeletedData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/messages/event-message-deleted'
}

export type PostWsMessagesEventMessageDeletedResponses = {
  /**
   * Event payload.
   */
  200: {
    deletedMessageId: number
  }
}

export type PostWsMessagesEventMessageDeletedResponse =
  PostWsMessagesEventMessageDeletedResponses[keyof PostWsMessagesEventMessageDeletedResponses]

export type PostWsConversationsEventConversationNewData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/conversations/event-conversation-new'
}

export type PostWsConversationsEventConversationNewResponses = {
  /**
   * Event payload.
   */
  200: ResponseConversationDto
}

export type PostWsConversationsEventConversationNewResponse =
  PostWsConversationsEventConversationNewResponses[keyof PostWsConversationsEventConversationNewResponses]

export type PostWsConversationsEventConversationDeletedData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/conversations/event-conversation-deleted'
}

export type PostWsConversationsEventConversationDeletedResponses = {
  /**
   * Event payload.
   */
  200: {
    deletedConversationId: number
  }
}

export type PostWsConversationsEventConversationDeletedResponse =
  PostWsConversationsEventConversationDeletedResponses[keyof PostWsConversationsEventConversationDeletedResponses]

export type PostWsUsersUserOnlineListRequestData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/users/user-online-list-request'
}

export type PostWsUsersUserOnlineListRequestResponses = {
  /**
   * No ack payload.
   */
  204: void
}

export type PostWsUsersUserOnlineListRequestResponse =
  PostWsUsersUserOnlineListRequestResponses[keyof PostWsUsersUserOnlineListRequestResponses]

export type PostWsUsersEventUserOnlineData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/users/event-user-online'
}

export type PostWsUsersEventUserOnlineResponses = {
  /**
   * Event payload.
   */
  200: number
}

export type PostWsUsersEventUserOnlineResponse =
  PostWsUsersEventUserOnlineResponses[keyof PostWsUsersEventUserOnlineResponses]

export type PostWsUsersEventUserOfflineData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/users/event-user-offline'
}

export type PostWsUsersEventUserOfflineResponses = {
  /**
   * Event payload.
   */
  200: number
}

export type PostWsUsersEventUserOfflineResponse =
  PostWsUsersEventUserOfflineResponses[keyof PostWsUsersEventUserOfflineResponses]

export type PostWsUsersEventUserOnlineListData = {
  body?: never
  path?: never
  query?: never
  url: '/ws/users/event-user-online-list'
}

export type PostWsUsersEventUserOnlineListResponses = {
  /**
   * Event payload.
   */
  200: Array<number>
}

export type PostWsUsersEventUserOnlineListResponse =
  PostWsUsersEventUserOnlineListResponses[keyof PostWsUsersEventUserOnlineListResponses]
